# Hypothesis using matrix

### matrix 사용 전

In [3]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [4]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [7]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')

b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [9]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [11]:
train = optimizer.minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "Prediction: ", hy_val)

0 Cost:  32883.62 Prediction:  [307.3999  381.48584 369.69754 401.70917 294.84265]
10 Cost:  14.672758 Prediction:  [147.03471 188.71144 179.76787 194.8791  147.79868]
20 Cost:  14.295796 Prediction:  [146.56393 188.11824 179.1976  194.25668 147.34058]
30 Cost:  14.220172 Prediction:  [146.57692 188.10655 179.20026 194.25816 147.32605]
40 Cost:  14.144953 Prediction:  [146.5913  188.09663 179.20464 194.2615  147.31287]
50 Cost:  14.070162 Prediction:  [146.60568 188.08679 179.20901 194.2649  147.29977]
60 Cost:  13.995714 Prediction:  [146.62001 188.07695 179.2134  194.26826 147.28668]
70 Cost:  13.921736 Prediction:  [146.6343  188.06714 179.21773 194.2716  147.27364]
80 Cost:  13.848127 Prediction:  [146.64854 188.05736 179.22209 194.27493 147.26062]
90 Cost:  13.774869 Prediction:  [146.66277 188.04759 179.22641 194.27827 147.24763]
100 Cost:  13.702101 Prediction:  [146.67693 188.03784 179.23071 194.2816  147.23471]
110 Cost:  13.629648 Prediction:  [146.69106 188.02814 179.23502 1

1150 Cost:  7.885802 Prediction:  [147.96909 187.1499  179.62396 194.58665 146.05212]
1160 Cost:  7.8447466 Prediction:  [147.97972 187.14262 179.62718 194.5892  146.04239]
1170 Cost:  7.8039412 Prediction:  [147.9903  187.13535 179.6304  194.59172 146.03267]
1180 Cost:  7.7633705 Prediction:  [148.00085 187.1281  179.63362 194.59424 146.023  ]
1190 Cost:  7.7229958 Prediction:  [148.01138 187.12085 179.63681 194.59674 146.01334]
1200 Cost:  7.68286 Prediction:  [148.02188 187.11363 179.64001 194.59923 146.00371]
1210 Cost:  7.6429276 Prediction:  [148.03235 187.10643 179.6432  194.60175 145.99411]
1220 Cost:  7.603219 Prediction:  [148.0428  187.09927 179.64638 194.60422 145.98453]
1230 Cost:  7.5637245 Prediction:  [148.05322 187.09213 179.64955 194.60674 145.97499]
1240 Cost:  7.524438 Prediction:  [148.0636  187.08499 179.65271 194.6092  145.96545]
1250 Cost:  7.4853835 Prediction:  [148.07394 187.07787 179.65585 194.61165 145.95595]
1260 Cost:  7.4464736 Prediction:  [148.08429 18

### matrix 사용 후

In [16]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [17]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [18]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [20]:
hypothesis = tf.matmul(X, W) + b

In [21]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [22]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [23]:
train = optimizer.minimize(cost)

In [24]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [25]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "Prediction: ", hy_val)

0 Cost:  174104.34 Prediction:  [[-213.20673]
 [-264.22845]
 [-256.0573 ]
 [-279.0525 ]
 [-203.71487]]
10 Cost:  20.390684 Prediction:  [[155.87021]
 [179.4056 ]
 [181.04675]
 [196.94437]
 [134.67265]]
20 Cost:  18.698729 Prediction:  [[156.97055]
 [180.75914]
 [182.3643 ]
 [198.38068]
 [135.71153]]
30 Cost:  18.60088 Prediction:  [[156.95753]
 [180.77446]
 [182.36331]
 [198.3811 ]
 [135.72966]]
40 Cost:  18.50359 Prediction:  [[156.94121]
 [180.7857 ]
 [182.35837]
 [198.37721]
 [135.74467]]
50 Cost:  18.406872 Prediction:  [[156.92491]
 [180.79689]
 [182.3534 ]
 [198.3733 ]
 [135.75961]]
60 Cost:  18.310633 Prediction:  [[156.90868]
 [180.80806]
 [182.34846]
 [198.36943]
 [135.77455]]
70 Cost:  18.214975 Prediction:  [[156.89249]
 [180.8192 ]
 [182.34355]
 [198.36557]
 [135.78943]]
80 Cost:  18.1198 Prediction:  [[156.87633]
 [180.8303 ]
 [182.33865]
 [198.3617 ]
 [135.80426]]
90 Cost:  18.025084 Prediction:  [[156.86021]
 [180.84138]
 [182.33372]
 [198.35783]
 [135.81906]]
100 Cost: 

1270 Cost:  9.789065 Prediction:  [[155.23746]
 [181.9575 ]
 [181.84114]
 [197.9653 ]
 [137.31436]]
1280 Cost:  9.73929 Prediction:  [[155.22583]
 [181.96553]
 [181.83762]
 [197.96246]
 [137.32513]]
1290 Cost:  9.689812 Prediction:  [[155.21423]
 [181.97351]
 [181.8341 ]
 [197.95963]
 [137.33588]]
1300 Cost:  9.640574 Prediction:  [[155.20267]
 [181.98149]
 [181.83061]
 [197.95679]
 [137.34659]]
1310 Cost:  9.591595 Prediction:  [[155.1911 ]
 [181.98941]
 [181.82709]
 [197.95393]
 [137.35725]]
1320 Cost:  9.542933 Prediction:  [[155.17961]
 [181.99734]
 [181.82362]
 [197.95113]
 [137.3679 ]]
1330 Cost:  9.494471 Prediction:  [[155.16812]
 [182.00523]
 [181.82011]
 [197.9483 ]
 [137.37852]]
1340 Cost:  9.446345 Prediction:  [[155.1567 ]
 [182.0131 ]
 [181.81667]
 [197.9455 ]
 [137.38911]]
1350 Cost:  9.3984375 Prediction:  [[155.14526]
 [182.02095]
 [181.81319]
 [197.94267]
 [137.39966]]
1360 Cost:  9.350739 Prediction:  [[155.13388]
 [182.02881]
 [181.80975]
 [197.9399 ]
 [137.41022]]


# 학습 데이터 파일 불러들이는 기능 추가하기

In [26]:
import numpy as np

In [38]:
tf.set_random_seed(777)    # for reproducibility

In [27]:
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)

> dtype을 하나로만 설정할 수 있다는 단점 -> 파일의 모든 값들이 float32여야 함

In [37]:
print(xy, len(xy))

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]] 25


In [32]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [34]:
print(x_data.shape, x_data, len(x_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25


In [35]:
print(y_data.shape, y_data)

(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [39]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [40]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [41]:
hypothesis = tf.matmul(X, W) + b

In [42]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [43]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [44]:
train = optimizer.minimize(cost)

In [45]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [51]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X: x_data, Y: y_data})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "Prediction: ", hy_val)

0 Cost:  9.010582 Prediction:  [[153.69383]
 [183.27333]
 [181.18553]
 [199.39513]
 [137.65149]
 [104.4024 ]
 [152.65892]
 [117.99997]
 [173.41896]
 [165.00229]
 [144.5174 ]
 [142.61546]
 [185.06801]
 [150.76442]
 [153.36386]
 [188.07605]
 [140.61452]
 [184.90091]
 [176.32957]
 [158.28125]
 [178.11603]
 [174.01746]
 [169.3506 ]
 [150.03328]
 [189.2182 ]]
10 Cost:  8.994725 Prediction:  [[153.69296]
 [183.27628]
 [181.18655]
 [199.39395]
 [137.65663]
 [104.40308]
 [152.65347]
 [117.98942]
 [173.41983]
 [164.99834]
 [144.51572]
 [142.61469]
 [185.07152]
 [150.77094]
 [153.35873]
 [188.07648]
 [140.62477]
 [184.89198]
 [176.33269]
 [158.28317]
 [178.11104]
 [174.0177 ]
 [169.34616]
 [150.03804]
 [189.22174]]
20 Cost:  8.978966 Prediction:  [[153.69208]
 [183.27924]
 [181.18759]
 [199.39276]
 [137.66176]
 [104.40378]
 [152.64804]
 [117.97892]
 [173.42068]
 [164.9944 ]
 [144.51402]
 [142.6139 ]
 [185.07503]
 [150.7774 ]
 [153.3536 ]
 [188.07689]
 [140.63498]
 [184.88309]
 [176.33578]
 [158.

670 Cost:  8.122544 Prediction:  [[153.63087 ]
 [183.45912 ]
 [181.24535 ]
 [199.32196 ]
 [137.972   ]
 [104.455086]
 [152.32442 ]
 [117.35334 ]
 [173.48384 ]
 [164.77943 ]
 [144.4152  ]
 [142.5768  ]
 [185.27687 ]
 [151.15416 ]
 [153.0515  ]
 [188.1083  ]
 [141.23509 ]
 [184.3516  ]
 [176.51047 ]
 [158.38948 ]
 [177.81084 ]
 [174.03949 ]
 [169.07695 ]
 [150.30882 ]
 [189.43542 ]]
680 Cost:  8.111627 Prediction:  [[153.62987 ]
 [183.46172 ]
 [181.2461  ]
 [199.32094 ]
 [137.97641 ]
 [104.45594 ]
 [152.31985 ]
 [117.344536]
 [173.48488 ]
 [164.77667 ]
 [144.41382 ]
 [142.57639 ]
 [185.27959 ]
 [151.1593  ]
 [153.04727 ]
 [188.10883 ]
 [141.24341 ]
 [184.34409 ]
 [176.51277 ]
 [158.3908  ]
 [177.80667 ]
 [174.03989 ]
 [169.0732  ]
 [150.31233 ]
 [189.43837 ]]
690 Cost:  8.100785 Prediction:  [[153.62889]
 [183.4643 ]
 [181.24686]
 [199.31995]
 [137.98083]
 [104.4568 ]
 [152.31532]
 [117.33577]
 [173.48593]
 [164.77394]
 [144.41245]
 [142.576  ]
 [185.28232]
 [151.16446]
 [153.04309]
 [18

1320 Cost:  7.5240865 Prediction:  [[153.56535]
 [183.61752]
 [181.28815]
 [199.26135]
 [138.23991]
 [104.51423]
 [152.0525 ]
 [116.82815]
 [173.55551]
 [164.62956]
 [144.33408]
 [142.5601 ]
 [185.43571]
 [151.45604]
 [152.80183]
 [188.1447 ]
 [141.72662]
 [183.9027 ]
 [176.64246]
 [158.46227]
 [177.56442]
 [174.06783]
 [168.85254]
 [150.50682]
 [189.61333]]
1330 Cost:  7.516432 Prediction:  [[153.56435]
 [183.6198 ]
 [181.2887 ]
 [199.2605 ]
 [138.24374]
 [104.51517]
 [152.04868]
 [116.82077]
 [173.55666]
 [164.62766]
 [144.33295]
 [142.55997]
 [185.43787]
 [151.46017]
 [152.79836]
 [188.14526]
 [141.73346]
 [183.89636]
 [176.64423]
 [158.4632 ]
 [177.56096]
 [174.0683 ]
 [168.84937]
 [150.50943]
 [189.61584]]
1340 Cost:  7.5088234 Prediction:  [[153.56332]
 [183.62206]
 [181.28925]
 [199.25961]
 [138.24753]
 [104.51611]
 [152.04485]
 [116.81339]
 [173.55777]
 [164.62575]
 [144.3318 ]
 [142.55983]
 [185.44002]
 [151.4643 ]
 [152.79486]
 [188.14584]
 [141.74025]
 [183.89003]
 [176.6459

In [52]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[183.61707]]
Other scores will be  [[190.03958]
 [174.3497 ]]


# 파일 크기가 너무 클 때 -> Queue Runners

In [56]:
filename_queue = tf.train.string_input_producer(
    ['data/data-01-test-score.csv'],  # 파일 이름들을 리스트화
    shuffle=False, 
    name='filename_queue'
)

In [57]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [58]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)   # record_defaults : 읽어올 때 각 필드의 값이 어떤 형태인지

In [60]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [62]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [64]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [65]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X: x_batch, Y: y_batch})
    
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "Prediction: ", hy_val)

0 Cost:  31676.12 Prediction:  [[-15.767508]
 [-18.951153]
 [ -9.204516]
 [-21.825422]
 [-12.221201]
 [-16.827452]
 [-10.728033]
 [-17.917984]
 [-14.516508]
 [-12.426974]]
10 Cost:  37.305016 Prediction:  [[165.07878]
 [152.76643]
 [142.51582]
 [136.20212]
 [186.70032]
 [154.08919]
 [150.6151 ]
 [182.56798]
 [143.22134]
 [184.17163]]
20 Cost:  31.27308 Prediction:  [[166.41348]
 [154.01947]
 [143.59895]
 [137.28978]
 [188.10934]
 [155.25462]
 [151.74521]
 [184.00143]
 [144.33621]
 [185.5085 ]]
30 Cost:  31.04649 Prediction:  [[166.4523 ]
 [154.072  ]
 [143.60919]
 [137.31935]
 [188.10724]
 [155.24702]
 [151.75658]
 [184.02794]
 [144.3339 ]
 [185.50905]]
40 Cost:  30.850552 Prediction:  [[166.48216]
 [154.1162 ]
 [143.6121 ]
 [137.34164]
 [188.09557]
 [155.23152]
 [151.76033]
 [184.04477]
 [144.32402]
 [185.50053]]
50 Cost:  30.656475 Prediction:  [[166.51184]
 [154.16011]
 [143.61494]
 [137.36377]
 [188.0839 ]
 [155.21603]
 [151.76398]
 [184.06146]
 [144.31418]
 [185.49194]]
60 Cost:  

740 Cost:  20.52613 Prediction:  [[168.29163]
 [156.76595]
 [143.776  ]
 [138.68336]
 [187.40451]
 [154.32541]
 [151.95474]
 [185.0629 ]
 [143.78033]
 [184.93045]]
750 Cost:  20.417774 Prediction:  [[168.3139 ]
 [156.79817]
 [143.7779 ]
 [138.69978]
 [187.39632]
 [154.3148 ]
 [151.95673]
 [185.07542]
 [143.77446]
 [184.92276]]
760 Cost:  20.310308 Prediction:  [[168.33609]
 [156.83023]
 [143.77975]
 [138.71611]
 [187.38812]
 [154.30421]
 [151.95868]
 [185.08789]
 [143.7686 ]
 [184.91507]]
770 Cost:  20.203703 Prediction:  [[168.35817]
 [156.86217]
 [143.7816 ]
 [138.73238]
 [187.37999]
 [154.29372]
 [151.96062]
 [185.10033]
 [143.7628 ]
 [184.9074 ]]
780 Cost:  20.09793 Prediction:  [[168.38019]
 [156.89398]
 [143.78345]
 [138.7486 ]
 [187.37192]
 [154.28326]
 [151.96255]
 [185.1127 ]
 [143.75706]
 [184.89975]]
790 Cost:  19.993069 Prediction:  [[168.4021 ]
 [156.92563]
 [143.78526]
 [138.76471]
 [187.36385]
 [154.27286]
 [151.96446]
 [185.12502]
 [143.75136]
 [184.8921 ]]
800 Cost:  1

1240 Cost:  16.053776 Prediction:  [[169.30191]
 [158.215  ]
 [143.85709]
 [139.42416]
 [187.04097]
 [153.85983]
 [152.03262]
 [185.63092]
 [143.538  ]
 [184.56137]]
1250 Cost:  15.981356 Prediction:  [[169.32011]
 [158.24083]
 [143.85846]
 [139.43745]
 [187.03459]
 [153.85178]
 [152.03377]
 [185.64116]
 [143.53413]
 [184.5543 ]]
1260 Cost:  15.909567 Prediction:  [[169.33823]
 [158.26657]
 [143.85982]
 [139.45065]
 [187.02826]
 [153.84375]
 [152.03488]
 [185.65132]
 [143.53027]
 [184.54726]]
1270 Cost:  15.838313 Prediction:  [[169.35628]
 [158.29219]
 [143.86119]
 [139.46382]
 [187.02196]
 [153.8358 ]
 [152.03603]
 [185.66148]
 [143.5265 ]
 [184.54024]]
1280 Cost:  15.76763 Prediction:  [[169.37425]
 [158.3177 ]
 [143.86252]
 [139.47693]
 [187.01569]
 [153.82787]
 [152.03712]
 [185.67157]
 [143.52272]
 [184.53319]]
1290 Cost:  15.697553 Prediction:  [[169.39214]
 [158.3431 ]
 [143.86386]
 [139.48997]
 [187.00945]
 [153.81999]
 [152.03822]
 [185.68163]
 [143.51898]
 [184.52617]]
1300 

1760 Cost:  12.951886 Prediction:  [[170.15752]
 [159.41924]
 [143.9179 ]
 [140.04526]
 [186.74986]
 [153.4959 ]
 [152.07549]
 [186.11165]
 [143.37883]
 [184.21062]]
1770 Cost:  12.903689 Prediction:  [[170.17227]
 [159.4398 ]
 [143.91887]
 [140.05592]
 [186.745  ]
 [153.48991]
 [152.076  ]
 [186.11993]
 [143.37653]
 [184.2042 ]]
1780 Cost:  12.855784 Prediction:  [[170.187  ]
 [159.4603 ]
 [143.91985]
 [140.06654]
 [186.74016]
 [153.48396]
 [152.0765 ]
 [186.12822]
 [143.37425]
 [184.1978 ]]
1790 Cost:  12.808317 Prediction:  [[170.20166]
 [159.48068]
 [143.9208 ]
 [140.07712]
 [186.73535]
 [153.47804]
 [152.07701]
 [186.13643]
 [143.372  ]
 [184.19138]]
1800 Cost:  12.761179 Prediction:  [[170.21623]
 [159.50099]
 [143.92177]
 [140.08765]
 [186.73055]
 [153.47215]
 [152.0775 ]
 [186.14464]
 [143.36977]
 [184.18498]]
1810 Cost:  12.714411 Prediction:  [[170.23077]
 [159.52121]
 [143.92271]
 [140.09813]
 [186.7258 ]
 [153.4663 ]
 [152.07797]
 [186.1528 ]
 [143.36755]
 [184.17862]]
1820

In [66]:
coord.request_stop()
coord.join(threads)

### shuffle_batch 라는 것도 있음!

In [67]:
# min_after_dequeue defines how big a buffer we will randomly sample
#   from -- bigger means better shuffling but slower start up and more
#   memory used.
# capacity must be larger than min_after_dequeue and the amount larger
#   determines the maximum we will prefetch.  Recommendation:
#   min_after_dequeue + (num_threads + a small safety margin) * batch_size

min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch(
   [example, label], batch_size=batch_size, capacity=capacity,
   min_after_dequeue=min_after_dequeue)

NameError: name 'batch_size' is not defined