# Softmax Classification

In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]

y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [13]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

num_classes = 3

W = tf.Variable(tf.random_normal([4, num_classes]), name='weight')
b = tf.Variable(tf.random_normal([num_classes]), name='bias')

# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            
    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 5.2833047
200 0.59377366
400 0.49835563
600 0.42327243
800 0.35504797
1000 0.28582948
1200 0.23183855
1400 0.21095693
1600 0.1933834
1800 0.17839393
2000 0.16547035
--------------
[[7.5406462e-02 9.2458242e-01 1.1167976e-05]] [1]
--------------
[[0.53511626 0.39730167 0.06758203]] [0]
--------------
[[1.8145514e-08 4.0236479e-04 9.9959761e-01]] [2]
--------------
[[7.5406529e-02 9.2458236e-01 1.1167975e-05]
 [5.3511614e-01 3.9730179e-01 6.7582086e-02]] [1 0]
