# Tensorboard (Neural Net for XOR)

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [3]:
X = tf.placeholder(tf.float32, [None, 2], name="x")
Y = tf.placeholder(tf.float32, [None, 1], name="y")

with tf.name_scope("Layer1"):
    W1 = tf.Variable(tf.random_normal([2, 2]), name='weight_1')
    b1 = tf.Variable(tf.random_normal([2]), name='bias_1')
    
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
    
    tf.summary.histogram("W1", W1)
    tf.summary.histogram("b1", b1)
    tf.summary.histogram("Layer1", layer1)
    
with tf.name_scope("Layer2"):
    W2 = tf.Variable(tf.random_normal([2, 1]), name="weight_2")
    b2 = tf.Variable(tf.random_normal([1]), name="bias_2")
    
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

    tf.summary.histogram("W2", W2)
    tf.summary.histogram("b2", b2)
    tf.summary.histogram("Hypothesis", hypothesis)
    
with tf.name_scope("Cost"):
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
    tf.summary.scalar("Cost", cost)
    
with tf.name_scope("Train"):
    train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)
    
    
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

tf.summary.scalar("accuracy", accuracy)

with tf.Session() as sess:
    # tensorboard --logdir=./logs/xor_logs
    merged_summary = tf.summary.merge_all()
    
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)
    
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, summary, cost_val = sess.run([train, merged_summary, cost], feed_dict={X: x_data, Y: y_data})
        
        writer.add_summary(summary, global_step=step)
        
        if step % 100 == 0:
            print(step, cost_val)
            
        h, p, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
        
        print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 0.69613093

Hypothesis:
[[0.41677654]
 [0.43355027]
 [0.48329148]
 [0.49170402]] 
Predicted:
[[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:
0.5

Hypothesis:
[[0.4226597 ]
 [0.43954763]
 [0.48886582]
 [0.49667698]] 
Predicted:
[[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:
0.5

Hypothesis:
[[0.42852104]
 [0.44553405]
 [0.49432382]
 [0.5015477 ]] 
Predicted:
[[0.]
 [0.]
 [0.]
 [1.]] 
Accuracy:
0.25

Hypothesis:
[[0.43432954]
 [0.45147753]
 [0.49959144]
 [0.50624144]] 
Predicted:
[[0.]
 [0.]
 [0.]
 [1.]] 
Accuracy:
0.25

Hypothesis:
[[0.4400481 ]
 [0.45733905]
 [0.50457406]
 [0.510662  ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.44563267]
 [0.46307325]
 [0.50917965]
 [0.51471555]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.45103303]
 [0.46862838]
 [0.51335496]
 [0.518346  ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.45619363]
 [0.47394744]
 [0.5170887 ]
 [0.5215383 ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothes


Hypothesis:
[[0.33227852]
 [0.64852405]
 [0.64834833]
 [0.3379981 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.3307403 ]
 [0.6498233 ]
 [0.650222  ]
 [0.33647627]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.32920465]
 [0.651123  ]
 [0.6520938 ]
 [0.33495522]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.3276718 ]
 [0.6524232 ]
 [0.65396327]
 [0.3334351 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.32614192]
 [0.65372354]
 [0.6558303 ]
 [0.33191597]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.32461497]
 [0.65502405]
 [0.6576944 ]
 [0.33039808]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.32309127]
 [0.65632445]
 [0.65955555]
 [0.32888156]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.32157078]
 [0.6576247 ]
 [0.6614132 ]
 [0.32736653]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.3200535


Hypothesis:
[[0.1385923 ]
 [0.8354672 ]
 [0.87285864]
 [0.13970129]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13803083]
 [0.8360811 ]
 [0.8734393 ]
 [0.13912691]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13747263]
 [0.83669186]
 [0.874016  ]
 [0.13855596]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13691778]
 [0.8372992 ]
 [0.8745887 ]
 [0.13798852]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13636634]
 [0.83790356]
 [0.8751576 ]
 [0.13742457]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13581817]
 [0.8385045 ]
 [0.8757225 ]
 [0.13686404]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13527322]
 [0.83910245]
 [0.8762835 ]
 [0.13630691]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13473149]
 [0.8396971 ]
 [0.87684083]
 [0.1357532 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.1341929


Hypothesis:
[[0.07585391]
 [0.90667087]
 [0.93441826]
 [0.07600111]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07563031]
 [0.9069341 ]
 [0.9346256 ]
 [0.07577575]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07540775]
 [0.90719616]
 [0.934832  ]
 [0.0755514 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07518613]
 [0.9074571 ]
 [0.93503726]
 [0.07532816]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07496556]
 [0.90771705]
 [0.93524146]
 [0.07510591]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07474605]
 [0.90797573]
 [0.9354447 ]
 [0.07488471]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0745275 ]
 [0.9082334 ]
 [0.93564695]
 [0.07466457]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.07430991]
 [0.9084898 ]
 [0.9358483 ]
 [0.07444535]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0740933


Hypothesis:
[[0.04677051]
 [0.94147784]
 [0.96067625]
 [0.04677879]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04666534]
 [0.9416058 ]
 [0.9607687 ]
 [0.04667336]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04656053]
 [0.9417333 ]
 [0.9608607 ]
 [0.04656835]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04645609]
 [0.9418604 ]
 [0.9609525 ]
 [0.04646371]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04635201]
 [0.9419871 ]
 [0.9610438 ]
 [0.04635939]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04624829]
 [0.9421134 ]
 [0.96113485]
 [0.04625553]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04614492]
 [0.9422391 ]
 [0.96122545]
 [0.04615191]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04604193]
 [0.9423646 ]
 [0.96131593]
 [0.0460487 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0459393


Hypothesis:
[[0.03156587]
 [0.96014076]
 [0.9738437 ]
 [0.03155718]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03150868]
 [0.96021146]
 [0.97389257]
 [0.03150001]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03145167]
 [0.96028215]
 [0.9739412 ]
 [0.03144294]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03139479]
 [0.9603526 ]
 [0.9739897 ]
 [0.03138613]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03133806]
 [0.96042275]
 [0.9740381 ]
 [0.03132936]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03128153]
 [0.9604928 ]
 [0.9740864 ]
 [0.03127282]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03122517]
 [0.96056265]
 [0.97413445]
 [0.03121643]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03116892]
 [0.96063226]
 [0.9741824 ]
 [0.03116017]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0311128


Hypothesis:
[[0.02300386]
 [0.97079575]
 [0.98109424]
 [0.02299629]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02296865]
 [0.97083986]
 [0.98112386]
 [0.02296105]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02293341]
 [0.9708838 ]
 [0.9811535 ]
 [0.02292589]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02289836]
 [0.9709278 ]
 [0.98118293]
 [0.02289083]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02286333]
 [0.9709716 ]
 [0.9812123 ]
 [0.02285583]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02282842]
 [0.9710152 ]
 [0.9812416 ]
 [0.02282089]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02279357]
 [0.9710588 ]
 [0.98127085]
 [0.02278605]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02275879]
 [0.9711023 ]
 [0.9813002 ]
 [0.02275133]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0227241


Hypothesis:
[[0.01759895]
 [0.9775778 ]
 [0.9856117 ]
 [0.01759422]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
1300 0.018169176

Hypothesis:
[[0.01757539]
 [0.9776074 ]
 [0.9856312 ]
 [0.01757066]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01755186]
 [0.97763705]
 [0.98565084]
 [0.01754714]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01752842]
 [0.97766656]
 [0.9856704 ]
 [0.0175237 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01750499]
 [0.97769606]
 [0.9856899 ]
 [0.0175003 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01748162]
 [0.9777256 ]
 [0.9857093 ]
 [0.01747692]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01745828]
 [0.9777549 ]
 [0.9857287 ]
 [0.01745362]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.017435  ]
 [0.9777843 ]
 [0.985748  ]
 [0.01743036]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypoth


Hypothesis:
[[0.01379182]
 [0.9823819 ]
 [0.9887664 ]
 [0.01378943]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01377538]
 [0.9824027 ]
 [0.98878   ]
 [0.01377303]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01375899]
 [0.9824234 ]
 [0.98879355]
 [0.01375662]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0137426 ]
 [0.9824441 ]
 [0.9888071 ]
 [0.01374025]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01372624]
 [0.98246485]
 [0.9888206 ]
 [0.01372391]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01370993]
 [0.9824854 ]
 [0.98883396]
 [0.01370761]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01369365]
 [0.98250616]
 [0.9888475 ]
 [0.01369133]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01367737]
 [0.9825266 ]
 [0.9888609 ]
 [0.01367506]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
1500 0.014092653

Hypoth


Hypothesis:
[[0.01114053]
 [0.98574114]
 [0.99095017]
 [0.01113973]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01112849]
 [0.98575646]
 [0.99096   ]
 [0.01112768]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01111645]
 [0.98577166]
 [0.99096996]
 [0.01111566]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01110443]
 [0.9857869 ]
 [0.99097973]
 [0.01110365]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01109243]
 [0.98580223]
 [0.99098957]
 [0.01109166]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01108046]
 [0.9858174 ]
 [0.9909994 ]
 [0.01107969]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0110685 ]
 [0.9858326 ]
 [0.99100924]
 [0.01106773]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01105656]
 [0.9858477 ]
 [0.99101907]
 [0.01105581]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0110446


Hypothesis:
[[0.00914717]
 [0.98827434]
 [0.99258476]
 [0.00914742]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00913807]
 [0.98828596]
 [0.9925922 ]
 [0.00913831]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00912897]
 [0.9882975 ]
 [0.9925996 ]
 [0.00912922]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0091199 ]
 [0.988309  ]
 [0.9926071 ]
 [0.00912016]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00911085]
 [0.9883206 ]
 [0.9926145 ]
 [0.00911109]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00910179]
 [0.9883321 ]
 [0.9926219 ]
 [0.00910204]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00909275]
 [0.9883436 ]
 [0.9926293 ]
 [0.00909301]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00908373]
 [0.98835504]
 [0.9926367 ]
 [0.00908398]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0090747


Hypothesis:
[[0.00759492]
 [0.99025166]
 [0.99385333]
 [0.00759581]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00758792]
 [0.99026066]
 [0.9938591 ]
 [0.00758881]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00758091]
 [0.99026954]
 [0.9938647 ]
 [0.0075818 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0075739 ]
 [0.99027854]
 [0.9938705 ]
 [0.00757481]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00756693]
 [0.9902874 ]
 [0.99387616]
 [0.00756782]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00755995]
 [0.9902963 ]
 [0.99388194]
 [0.00756085]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00755299]
 [0.9903052 ]
 [0.9938876 ]
 [0.00755389]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00754602]
 [0.99031407]
 [0.99389327]
 [0.00754692]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0075390


Hypothesis:
[[0.00644122]
 [0.9917243 ]
 [0.99479383]
 [0.00644246]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00643562]
 [0.99173135]
 [0.9947983 ]
 [0.00643686]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00643004]
 [0.9917385 ]
 [0.99480295]
 [0.00643129]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00642446]
 [0.99174565]
 [0.9948074 ]
 [0.00642572]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00641889]
 [0.9917528 ]
 [0.994812  ]
 [0.00642015]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00641333]
 [0.99175984]
 [0.9948165 ]
 [0.00641459]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00640776]
 [0.991767  ]
 [0.9948211 ]
 [0.00640903]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00640222]
 [0.991774  ]
 [0.9948256 ]
 [0.00640347]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0063966


Hypothesis:
[[0.00552762]
 [0.992892  ]
 [0.99553704]
 [0.00552907]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00552307]
 [0.99289787]
 [0.9955407 ]
 [0.00552452]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00551853]
 [0.99290365]
 [0.9955444 ]
 [0.00551998]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00551399]
 [0.9929095 ]
 [0.9955481 ]
 [0.00551545]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00550945]
 [0.9929153 ]
 [0.99555176]
 [0.00551091]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00550493]
 [0.99292105]
 [0.99555546]
 [0.00550638]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00550041]
 [0.9929269 ]
 [0.9955591 ]
 [0.00550187]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0054959 ]
 [0.9929327 ]
 [0.9955628 ]
 [0.00549735]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0054913


Hypothesis:
[[0.0047574 ]
 [0.99387795]
 [0.99616253]
 [0.00475895]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00475367]
 [0.99388266]
 [0.9961655 ]
 [0.00475523]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00474995]
 [0.9938875 ]
 [0.99616855]
 [0.00475151]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00474623]
 [0.9938922 ]
 [0.99617153]
 [0.00474779]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00474252]
 [0.9938969 ]
 [0.9961746 ]
 [0.00474408]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00473882]
 [0.9939017 ]
 [0.99617755]
 [0.00474037]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00473511]
 [0.99390644]
 [0.99618065]
 [0.00473667]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0047314 ]
 [0.99391115]
 [0.9961836 ]
 [0.00473297]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0047277


Hypothesis:
[[0.00416937]
 [0.9946313 ]
 [0.9966394 ]
 [0.00417095]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00416624]
 [0.9946353 ]
 [0.9966419 ]
 [0.00416782]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00416311]
 [0.99463934]
 [0.9966445 ]
 [0.00416469]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00415998]
 [0.99464333]
 [0.99664694]
 [0.00416157]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00415686]
 [0.9946473 ]
 [0.99664956]
 [0.00415845]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00415374]
 [0.9946514 ]
 [0.99665207]
 [0.00415532]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00415062]
 [0.9946554 ]
 [0.9966545 ]
 [0.0041522 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00414751]
 [0.99465936]
 [0.99665713]
 [0.00414909]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0041443


Hypothesis:
[[0.00363279]
 [0.99531955]
 [0.997074  ]
 [0.00363436]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00363017]
 [0.9953229 ]
 [0.99707615]
 [0.00363173]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00362755]
 [0.9953263 ]
 [0.9970783 ]
 [0.00362911]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00362492]
 [0.9953296 ]
 [0.9970804 ]
 [0.00362649]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00362231]
 [0.995333  ]
 [0.99708253]
 [0.00362388]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0036197 ]
 [0.99533635]
 [0.99708456]
 [0.00362127]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00361709]
 [0.99533963]
 [0.9970867 ]
 [0.00361865]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00361448]
 [0.9953431 ]
 [0.99708885]
 [0.00361604]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0036118


Hypothesis:
[[0.00315717]
 [0.99593   ]
 [0.9974589 ]
 [0.00315868]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00315497]
 [0.9959329 ]
 [0.9974606 ]
 [0.00315649]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00315278]
 [0.9959357 ]
 [0.9974624 ]
 [0.00315429]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00315059]
 [0.99593854]
 [0.9974642 ]
 [0.0031521 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0031484 ]
 [0.99594134]
 [0.99746597]
 [0.00314991]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314621]
 [0.9959442 ]
 [0.99746776]
 [0.00314773]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314402]
 [0.99594694]
 [0.9974694 ]
 [0.00314554]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314184]
 [0.99594975]
 [0.9974712 ]
 [0.00314335]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0031396


Hypothesis:
[[0.00277408]
 [0.9964223 ]
 [0.9977685 ]
 [0.00277553]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00277221]
 [0.9964246 ]
 [0.9977701 ]
 [0.00277366]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00277034]
 [0.996427  ]
 [0.9977715 ]
 [0.00277179]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00276847]
 [0.9964295 ]
 [0.997773  ]
 [0.00276992]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00276661]
 [0.9964318 ]
 [0.99777454]
 [0.00276806]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00276475]
 [0.9964342 ]
 [0.997776  ]
 [0.0027662 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00276289]
 [0.9964366 ]
 [0.9977775 ]
 [0.00276433]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00276103]
 [0.996439  ]
 [0.9977791 ]
 [0.00276248]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0027591


Hypothesis:
[[0.00242784]
 [0.99686736]
 [0.99804807]
 [0.00242921]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00242626]
 [0.9968694 ]
 [0.9980494 ]
 [0.00242762]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00242467]
 [0.9968714 ]
 [0.9980507 ]
 [0.00242604]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00242309]
 [0.99687344]
 [0.998052  ]
 [0.00242446]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00242151]
 [0.9968755 ]
 [0.9980532 ]
 [0.00242288]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00241993]
 [0.99687755]
 [0.9980545 ]
 [0.0024213 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00241834]
 [0.9968796 ]
 [0.9980558 ]
 [0.00241972]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00241677]
 [0.9968816 ]
 [0.99805707]
 [0.00241814]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0024151


Hypothesis:
[[0.00213701]
 [0.9972415 ]
 [0.9982828 ]
 [0.00213829]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00213565]
 [0.9972433 ]
 [0.9982838 ]
 [0.00213694]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0021343 ]
 [0.99724495]
 [0.998285  ]
 [0.00213558]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00213294]
 [0.99724674]
 [0.99828607]
 [0.00213422]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00213158]
 [0.9972485 ]
 [0.99828714]
 [0.00213287]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00213023]
 [0.99725026]
 [0.9982882 ]
 [0.00213151]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212887]
 [0.9972519 ]
 [0.9982893 ]
 [0.00213016]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212753]
 [0.9972537 ]
 [0.9982905 ]
 [0.00212881]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0021261


Hypothesis:
[[0.00189532]
 [0.9975526 ]
 [0.99847764]
 [0.00189652]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00189415]
 [0.9975541 ]
 [0.9984786 ]
 [0.00189535]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00189297]
 [0.9975556 ]
 [0.99847955]
 [0.00189417]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0018918 ]
 [0.99755716]
 [0.9984805 ]
 [0.00189299]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00189062]
 [0.9975586 ]
 [0.99848145]
 [0.00189182]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00188945]
 [0.99756014]
 [0.9984824 ]
 [0.00189065]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00188828]
 [0.9975617 ]
 [0.99848336]
 [0.00188947]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0018871]
 [0.9975631]
 [0.9984843]
 [0.0018883]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00188594]
 


Hypothesis:
[[0.00167623]
 [0.99783474]
 [0.99865425]
 [0.00167734]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167521]
 [0.99783605]
 [0.9986551 ]
 [0.00167632]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167419]
 [0.99783736]
 [0.9986559 ]
 [0.0016753 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167318]
 [0.9978387 ]
 [0.99865663]
 [0.00167429]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167216]
 [0.9978399 ]
 [0.99865746]
 [0.00167327]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167115]
 [0.99784124]
 [0.9986583 ]
 [0.00167225]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00167013]
 [0.99784255]
 [0.99865913]
 [0.00167124]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00166912]
 [0.99784386]
 [0.99865997]
 [0.00167022]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0016681


Hypothesis:
[[0.00148801]
 [0.9980773 ]
 [0.9988059 ]
 [0.00148904]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148713]
 [0.99807847]
 [0.9988066 ]
 [0.00148816]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148624]
 [0.99807954]
 [0.9988073 ]
 [0.00148727]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148536]
 [0.99808073]
 [0.998808  ]
 [0.00148638]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148447]
 [0.9980818 ]
 [0.99880874]
 [0.0014855 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148359]
 [0.998083  ]
 [0.99880946]
 [0.00148461]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0014827 ]
 [0.99808407]
 [0.9988102 ]
 [0.00148373]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00148182]
 [0.99808526]
 [0.9988109 ]
 [0.00148285]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0014809


Hypothesis:
[[0.00131998]
 [0.99829394]
 [0.9989411 ]
 [0.00132092]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0013192 ]
 [0.9982949 ]
 [0.9989417 ]
 [0.00132015]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00131844]
 [0.99829584]
 [0.9989423 ]
 [0.00131938]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00131766]
 [0.9982969 ]
 [0.99894303]
 [0.00131861]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0013169 ]
 [0.99829787]
 [0.9989436 ]
 [0.00131784]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00131613]
 [0.9982988 ]
 [0.9989442 ]
 [0.00131707]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00131535]
 [0.9982999 ]
 [0.9989448 ]
 [0.0013163 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00131459]
 [0.99830085]
 [0.9989454 ]
 [0.00131553]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0013138


Hypothesis:
[[0.00117467]
 [0.99848133]
 [0.99905807]
 [0.00117553]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117399]
 [0.99848217]
 [0.99905854]
 [0.00117486]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117331]
 [0.998483  ]
 [0.99905914]
 [0.00117418]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117264]
 [0.99848396]
 [0.9990596 ]
 [0.00117351]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117197]
 [0.9984848 ]
 [0.9990602 ]
 [0.00117283]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117129]
 [0.9984856 ]
 [0.9990607 ]
 [0.00117215]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00117062]
 [0.9984865 ]
 [0.9990613 ]
 [0.00117148]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00116994]
 [0.99848735]
 [0.99906176]
 [0.00117081]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0011692


Hypothesis:
[[0.0010472]
 [0.9986457]
 [0.9991605]
 [0.001048 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104661]
 [0.99864644]
 [0.999161  ]
 [0.0010474 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104602]
 [0.9986473 ]
 [0.9991615 ]
 [0.00104681]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104542]
 [0.998648  ]
 [0.99916196]
 [0.00104622]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104483]
 [0.9986488 ]
 [0.99916244]
 [0.00104562]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104424]
 [0.99864954]
 [0.9991629 ]
 [0.00104503]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104364]
 [0.9986504 ]
 [0.9991634 ]
 [0.00104444]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104305]
 [0.9986511 ]
 [0.99916387]
 [0.00104385]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104246]
 


Hypothesis:
[[9.3504059e-04]
 [9.9879044e-01]
 [9.9925059e-01]
 [9.3577040e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3451602e-04]
 [9.9879116e-01]
 [9.9925107e-01]
 [9.3524542e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3399518e-04]
 [9.9879187e-01]
 [9.9925143e-01]
 [9.3472167e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3347294e-04]
 [9.9879241e-01]
 [9.9925190e-01]
 [9.3419990e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3294843e-04]
 [9.9879313e-01]
 [9.9925226e-01]
 [9.3367673e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3242672e-04]
 [9.9879384e-01]
 [9.9925274e-01]
 [9.3315460e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3190541e-04]
 [9.9879444e-01]
 [9.9925321e-01]
 [9.3263201e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.3138433e-04]
 [9.9879515e-01]
 [9.9925357e-01


Hypothesis:
[[8.4024254e-04]
 [9.9891281e-01]
 [9.9932683e-01]
 [8.4091298e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3977793e-04]
 [9.9891353e-01]
 [9.9932718e-01]
 [8.4044633e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3931151e-04]
 [9.9891412e-01]
 [9.9932766e-01]
 [8.3998119e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3884783e-04]
 [9.9891472e-01]
 [9.9932802e-01]
 [8.3951704e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3838432e-04]
 [9.9891531e-01]
 [9.9932837e-01]
 [8.3905325e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3792111e-04]
 [9.9891591e-01]
 [9.9932873e-01]
 [8.3858729e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3745731e-04]
 [9.9891651e-01]
 [9.9932909e-01]
 [8.3812466e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.3699304e-04]
 [9.9891710e-01]
 [9.9932945e-01


Hypothesis:
[[7.546793e-04]
 [9.990233e-01]
 [9.993956e-01]
 [7.552937e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5426517e-04]
 [9.9902391e-01]
 [9.9939585e-01]
 [7.5488072e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.538534e-04]
 [9.990244e-01]
 [9.993962e-01]
 [7.544664e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5343973e-04]
 [9.9902499e-01]
 [9.9939656e-01]
 [7.5405312e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5302768e-04]
 [9.9902546e-01]
 [9.9939692e-01]
 [7.5364148e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5261446e-04]
 [9.9902606e-01]
 [9.9939716e-01]
 [7.5322646e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5220293e-04]
 [9.9902654e-01]
 [9.9939752e-01]
 [7.5281534e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5178943e-04]
 [9.9902713e-01]
 [9.9939787e-01]
 [7.52


Hypothesis:
[[6.8334804e-04]
 [9.9911553e-01]
 [9.9945277e-01]
 [6.8391225e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.829762e-04]
 [9.991160e-01]
 [9.994531e-01]
 [6.835414e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.8260665e-04]
 [9.9911648e-01]
 [9.9945349e-01]
 [6.8317022e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.8223558e-04]
 [9.9911696e-01]
 [9.9945372e-01]
 [6.8279955e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.8186544e-04]
 [9.9911743e-01]
 [9.9945396e-01]
 [6.8242836e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.814935e-04]
 [9.991179e-01]
 [9.994543e-01]
 [6.820581e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.8112439e-04]
 [9.9911839e-01]
 [9.9945456e-01]
 [6.8168738e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.8075344e-04]
 [9.9911886e-01]
 [9.9945492e-01]
 [6.81


Hypothesis:
[[6.2329206e-04]
 [9.9919313e-01]
 [9.9950099e-01]
 [6.2381563e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2295655e-04]
 [9.9919349e-01]
 [9.9950135e-01]
 [6.2347919e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2261941e-04]
 [9.9919397e-01]
 [9.9950159e-01]
 [6.2314357e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2228536e-04]
 [9.9919444e-01]
 [9.9950182e-01]
 [6.2280812e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2195037e-04]
 [9.9919480e-01]
 [9.9950206e-01]
 [6.2247162e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
5900 0.0006370995

Hypothesis:
[[6.2161556e-04]
 [9.9919528e-01]
 [9.9950242e-01]
 [6.2213832e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2128092e-04]
 [9.9919575e-01]
 [9.9950266e-01]
 [6.2180159e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.2094530e-04]
 [9.9919611e-0


Hypothesis:
[[5.661530e-04]
 [9.992669e-01]
 [9.995468e-01]
 [5.666329e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6585087e-04]
 [9.9926740e-01]
 [9.9954706e-01]
 [5.6633161e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6554895e-04]
 [9.9926776e-01]
 [9.9954730e-01]
 [5.6602940e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6524551e-04]
 [9.9926811e-01]
 [9.9954754e-01]
 [5.6572573e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.649439e-04]
 [9.992685e-01]
 [9.995478e-01]
 [5.654244e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6464243e-04]
 [9.9926895e-01]
 [9.9954802e-01]
 [5.6512322e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6434167e-04]
 [9.9926931e-01]
 [9.9954826e-01]
 [5.6482060e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.6403998e-04]
 [9.9926966e-01]
 [9.9954849e-01]
 [5.64


Hypothesis:
[[5.1077909e-04]
 [9.9933857e-01]
 [9.9959129e-01]
 [5.1121990e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.1050750e-04]
 [9.9933881e-01]
 [9.9959153e-01]
 [5.1094906e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.1023654e-04]
 [9.9933916e-01]
 [9.9959177e-01]
 [5.1067781e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.099657e-04]
 [9.993395e-01]
 [9.995920e-01]
 [5.104058e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.096955e-04]
 [9.993399e-01]
 [9.995921e-01]
 [5.101349e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.0942402e-04]
 [9.9934024e-01]
 [9.9959236e-01]
 [5.0986366e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.091541e-04]
 [9.993406e-01]
 [9.995926e-01]
 [5.095940e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.0888432e-04]
 [9.9934095e-01]
 [9.9959284e-01]
 [5.093225


Hypothesis:
[[4.6163821e-04]
 [9.9940205e-01]
 [9.9963069e-01]
 [4.6204100e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6139405e-04]
 [9.9940240e-01]
 [9.9963093e-01]
 [4.6179796e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6115043e-04]
 [9.9940276e-01]
 [9.9963105e-01]
 [4.6155375e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6090654e-04]
 [9.9940300e-01]
 [9.9963129e-01]
 [4.6131093e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6066410e-04]
 [9.9940336e-01]
 [9.9963152e-01]
 [4.6106649e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6042132e-04]
 [9.9940372e-01]
 [9.9963164e-01]
 [4.6082307e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.6017912e-04]
 [9.9940395e-01]
 [9.9963188e-01]
 [4.6058107e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.5993575e-04]
 [9.9940431e-01]
 [9.9963212e-01


Hypothesis:
[[4.2031889e-04]
 [9.9945551e-01]
 [9.9966383e-01]
 [4.2068848e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.2009618e-04]
 [9.9945575e-01]
 [9.9966395e-01]
 [4.2046796e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1987520e-04]
 [9.9945611e-01]
 [9.9966419e-01]
 [4.2024595e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1965430e-04]
 [9.9945635e-01]
 [9.9966431e-01]
 [4.2002488e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1943355e-04]
 [9.9945658e-01]
 [9.9966455e-01]
 [4.1980392e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1921408e-04]
 [9.9945694e-01]
 [9.9966466e-01]
 [4.1958349e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1899315e-04]
 [9.9945718e-01]
 [9.9966490e-01]
 [4.1936315e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.1877391e-04]
 [9.9945754e-01]
 [9.9966502e-01


Hypothesis:
[[3.8150136e-04]
 [9.9950576e-01]
 [9.9969494e-01]
 [3.8184045e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8130282e-04]
 [9.9950600e-01]
 [9.9969506e-01]
 [3.8164103e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8110223e-04]
 [9.9950624e-01]
 [9.9969530e-01]
 [3.8144246e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8090392e-04]
 [9.9950647e-01]
 [9.9969542e-01]
 [3.8124248e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8070424e-04]
 [9.9950671e-01]
 [9.9969566e-01]
 [3.8104266e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8050540e-04]
 [9.9950707e-01]
 [9.9969578e-01]
 [3.8084437e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8030668e-04]
 [9.9950731e-01]
 [9.9969590e-01]
 [3.8064545e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.8010807e-04]
 [9.9950755e-01]
 [9.9969614e-01


Hypothesis:
[[3.5315851e-04]
 [9.9954236e-01]
 [9.9971765e-01]
 [3.5347583e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5297478e-04]
 [9.9954259e-01]
 [9.9971777e-01]
 [3.5329189e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5279040e-04]
 [9.9954283e-01]
 [9.9971789e-01]
 [3.5310804e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5260717e-04]
 [9.9954307e-01]
 [9.9971813e-01]
 [3.5292527e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5242466e-04]
 [9.9954331e-01]
 [9.9971825e-01]
 [3.5274198e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5224162e-04]
 [9.9954349e-01]
 [9.9971837e-01]
 [3.5255941e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5205932e-04]
 [9.9954373e-01]
 [9.9971849e-01]
 [3.5237562e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5187576e-04]
 [9.9954396e-01]
 [9.9971861e-01


Hypothesis:
[[3.3215748e-04]
 [9.9956959e-01]
 [9.9973446e-01]
 [3.3245783e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3198495e-04]
 [9.9956983e-01]
 [9.9973458e-01]
 [3.3228574e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3181251e-04]
 [9.9957007e-01]
 [9.9973470e-01]
 [3.3211315e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3164013e-04]
 [9.9957031e-01]
 [9.9973494e-01]
 [3.3194062e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3146850e-04]
 [9.9957043e-01]
 [9.9973506e-01]
 [3.3176882e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3129632e-04]
 [9.9957067e-01]
 [9.9973518e-01]
 [3.3159714e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3112423e-04]
 [9.9957091e-01]
 [9.9973530e-01]
 [3.3142423e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.3095287e-04]
 [9.9957114e-01]
 [9.9973541e-01


Hypothesis:
[[3.0858070e-04]
 [9.9960011e-01]
 [9.9975342e-01]
 [3.0886088e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0842010e-04]
 [9.9960035e-01]
 [9.9975353e-01]
 [3.0870133e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0826079e-04]
 [9.9960047e-01]
 [9.9975365e-01]
 [3.0854187e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0810034e-04]
 [9.9960071e-01]
 [9.9975377e-01]
 [3.0838128e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0794120e-04]
 [9.9960095e-01]
 [9.9975389e-01]
 [3.0822257e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0778180e-04]
 [9.9960107e-01]
 [9.9975401e-01]
 [3.0806189e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0762280e-04]
 [9.9960130e-01]
 [9.9975413e-01]
 [3.0790272e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.0746331e-04]
 [9.9960154e-01]
 [9.9975425e-01


Hypothesis:
[[2.7859694e-04]
 [9.9963892e-01]
 [9.9977738e-01]
 [2.7885154e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7845250e-04]
 [9.9963903e-01]
 [9.9977750e-01]
 [2.7870800e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7830972e-04]
 [9.9963927e-01]
 [9.9977762e-01]
 [2.7856507e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7816594e-04]
 [9.9963951e-01]
 [9.9977773e-01]
 [2.7842118e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7802275e-04]
 [9.9963963e-01]
 [9.9977785e-01]
 [2.7827788e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7787965e-04]
 [9.9963987e-01]
 [9.9977797e-01]
 [2.7813463e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.7773611e-04]
 [9.9963999e-01]
 [9.9977809e-01]
 [2.7799042e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.775926e-04]
 [9.996402e-01]
 [9.997782e-01]
 


Hypothesis:
[[2.5199997e-04]
 [9.9967337e-01]
 [9.9979872e-01]
 [2.5223265e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5187075e-04]
 [9.9967349e-01]
 [9.9979883e-01]
 [2.5210282e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5174208e-04]
 [9.9967372e-01]
 [9.9979883e-01]
 [2.5197354e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5161199e-04]
 [9.9967384e-01]
 [9.9979895e-01]
 [2.5184432e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5148297e-04]
 [9.9967396e-01]
 [9.9979907e-01]
 [2.5171469e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5135401e-04]
 [9.9967420e-01]
 [9.9979919e-01]
 [2.5158562e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.512246e-04]
 [9.996743e-01]
 [9.997993e-01]
 [2.514571e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.5109533e-04]
 [9.9967456e-01]
 [9.9979943e-01]
 [


Hypothesis:
[[2.2860539e-04]
 [9.9970359e-01]
 [9.9981743e-01]
 [2.2881779e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2848860e-04]
 [9.9970371e-01]
 [9.9981755e-01]
 [2.2870046e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2837186e-04]
 [9.9970382e-01]
 [9.9981755e-01]
 [2.2858403e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2825475e-04]
 [9.9970406e-01]
 [9.9981767e-01]
 [2.2846724e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2813899e-04]
 [9.9970418e-01]
 [9.9981779e-01]
 [2.2835008e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2802199e-04]
 [9.9970430e-01]
 [9.9981791e-01]
 [2.2823298e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2790549e-04]
 [9.9970442e-01]
 [9.9981791e-01]
 [2.2811680e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.2778950e-04]
 [9.9970466e-01]
 [9.9981803e-01


Hypothesis:
[[2.0884785e-04]
 [9.9972922e-01]
 [9.9983323e-01]
 [2.0904308e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0874152e-04]
 [9.9972934e-01]
 [9.9983323e-01]
 [2.0893627e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0863488e-04]
 [9.9972945e-01]
 [9.9983335e-01]
 [2.0883032e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0852868e-04]
 [9.9972957e-01]
 [9.9983346e-01]
 [2.0872361e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0842193e-04]
 [9.9972981e-01]
 [9.9983358e-01]
 [2.0861677e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0831505e-04]
 [9.9972993e-01]
 [9.9983358e-01]
 [2.0851019e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0820901e-04]
 [9.9973005e-01]
 [9.9983370e-01]
 [2.0840406e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.0810263e-04]
 [9.9973017e-01]
 [9.9983382e-01


Hypothesis:
[[1.9366358e-04]
 [9.9974889e-01]
 [9.9984539e-01]
 [1.9384683e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9356482e-04]
 [9.9974900e-01]
 [9.9984539e-01]
 [1.9374836e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9346610e-04]
 [9.9974912e-01]
 [9.9984550e-01]
 [1.9364954e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9336816e-04]
 [9.9974924e-01]
 [9.9984562e-01]
 [1.9355043e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9326920e-04]
 [9.9974936e-01]
 [9.9984562e-01]
 [1.9345208e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9317062e-04]
 [9.9974948e-01]
 [9.9984574e-01]
 [1.9335342e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9307210e-04]
 [9.9974960e-01]
 [9.9984586e-01]
 [1.9325482e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.9297365e-04]
 [9.9974972e-01]
 [9.9984586e-01


Hypothesis:
[[1.7590635e-04]
 [9.9977189e-01]
 [9.9985957e-01]
 [1.7607349e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7581647e-04]
 [9.9977201e-01]
 [9.9985957e-01]
 [1.7598452e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7572714e-04]
 [9.9977213e-01]
 [9.9985969e-01]
 [1.7589478e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7563836e-04]
 [9.9977225e-01]
 [9.9985981e-01]
 [1.7580559e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7554862e-04]
 [9.9977237e-01]
 [9.9985981e-01]
 [1.7571574e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7545992e-04]
 [9.9977249e-01]
 [9.9985993e-01]
 [1.7562664e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7537027e-04]
 [9.9977261e-01]
 [9.9985993e-01]
 [1.7553689e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.7528099e-04]
 [9.9977273e-01]
 [9.9986005e-01


Hypothesis:
[[1.6127861e-04]
 [9.9979085e-01]
 [9.9987125e-01]
 [1.6143339e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6119759e-04]
 [9.9979097e-01]
 [9.9987125e-01]
 [1.6135137e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6111539e-04]
 [9.9979109e-01]
 [9.9987137e-01]
 [1.6126969e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
8500 0.00016499968

Hypothesis:
[[1.6103382e-04]
 [9.9979120e-01]
 [9.9987149e-01]
 [1.6118775e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6095201e-04]
 [9.9979120e-01]
 [9.9987149e-01]
 [1.6110585e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6087054e-04]
 [9.9979132e-01]
 [9.9987161e-01]
 [1.6102461e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6078880e-04]
 [9.9979144e-01]
 [9.9987161e-01]
 [1.6094248e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.6070741e-04]
 [9.9979156e-


Hypothesis:
[[1.4751853e-04]
 [9.9980861e-01]
 [9.9988222e-01]
 [1.4766067e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4744428e-04]
 [9.9980873e-01]
 [9.9988234e-01]
 [1.4758606e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4736950e-04]
 [9.9980885e-01]
 [9.9988234e-01]
 [1.4751122e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4729518e-04]
 [9.9980897e-01]
 [9.9988246e-01]
 [1.4743656e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4722077e-04]
 [9.9980909e-01]
 [9.9988246e-01]
 [1.4736177e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4714582e-04]
 [9.9980909e-01]
 [9.9988258e-01]
 [1.4728733e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4707148e-04]
 [9.9980921e-01]
 [9.9988258e-01]
 [1.4721234e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.4699703e-04]
 [9.9980932e-01]
 [9.9988270e-01


Hypothesis:
[[1.3542778e-04]
 [9.9982435e-01]
 [9.9989188e-01]
 [1.3555879e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3535935e-04]
 [9.9982446e-01]
 [9.9989200e-01]
 [1.3548977e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3529096e-04]
 [9.9982446e-01]
 [9.9989200e-01]
 [1.3542132e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3522235e-04]
 [9.9982458e-01]
 [9.9989212e-01]
 [1.3535238e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3515403e-04]
 [9.9982470e-01]
 [9.9989212e-01]
 [1.3528425e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3508547e-04]
 [9.9982470e-01]
 [9.9989223e-01]
 [1.3521590e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3501722e-04]
 [9.9982482e-01]
 [9.9989223e-01]
 [1.3514732e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.3494876e-04]
 [9.9982494e-01]
 [9.9989223e-01


Hypothesis:
[[1.2626853e-04]
 [9.9983621e-01]
 [9.9989927e-01]
 [1.2638947e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2620521e-04]
 [9.9983621e-01]
 [9.9989927e-01]
 [1.2632608e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2614168e-04]
 [9.9983633e-01]
 [9.9989939e-01]
 [1.2626250e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2607819e-04]
 [9.9983644e-01]
 [9.9989939e-01]
 [1.2619894e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2601448e-04]
 [9.9983656e-01]
 [9.9989951e-01]
 [1.2613494e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2595105e-04]
 [9.9983656e-01]
 [9.9989951e-01]
 [1.2607170e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2588766e-04]
 [9.9983668e-01]
 [9.9989951e-01]
 [1.2600799e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.2582405e-04]
 [9.9983680e-01]
 [9.9989963e-01


Hypothesis:
[[1.15425188e-04]
 [9.99850273e-01]
 [9.99907970e-01]
 [1.15535535e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.1536698e-04]
 [9.9985027e-01]
 [9.9990797e-01]
 [1.1547727e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.15309027e-04]
 [9.99850392e-01]
 [9.99907970e-01]
 [1.15419476e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.1525088e-04]
 [9.9985051e-01]
 [9.9990809e-01]
 [1.1536149e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.15192975e-04]
 [9.99850512e-01]
 [9.99908090e-01]
 [1.15303308e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.15135095e-04]
 [9.99850631e-01]
 [9.99908209e-01]
 [1.15245377e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.1507703e-04]
 [9.9985063e-01]
 [9.9990821e-01]
 [1.1518748e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.15019437e-04]
 [9.99850750e-0


Hypothesis:
[[1.05267129e-04]
 [9.99863386e-01]
 [9.99916077e-01]
 [1.05368366e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.05214145e-04]
 [9.99863505e-01]
 [9.99916077e-01]
 [1.05315317e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.0516098e-04]
 [9.9986351e-01]
 [9.9991608e-01]
 [1.0526231e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.0510814e-04]
 [9.9986362e-01]
 [9.9991620e-01]
 [1.0520923e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.0505544e-04]
 [9.9986362e-01]
 [9.9991620e-01]
 [1.0515647e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.0500266e-04]
 [9.9986374e-01]
 [9.9991620e-01]
 [1.0510363e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.04949904e-04]
 [9.99863863e-01]
 [9.99916315e-01]
 [1.05050829e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[1.0489707e-04]
 [9.9986386e-01]
 [9


Hypothesis:
[[9.6492586e-05]
 [9.9987483e-01]
 [9.9992299e-01]
 [9.6585747e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6444477e-05]
 [9.9987483e-01]
 [9.9992311e-01]
 [9.6537406e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6396019e-05]
 [9.9987495e-01]
 [9.9992311e-01]
 [9.6489101e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6347962e-05]
 [9.9987495e-01]
 [9.9992311e-01]
 [9.6440992e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6299736e-05]
 [9.9987507e-01]
 [9.9992323e-01]
 [9.6392527e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6251446e-05]
 [9.9987507e-01]
 [9.9992323e-01]
 [9.6344011e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6203279e-05]
 [9.9987519e-01]
 [9.9992323e-01]
 [9.6295975e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.6155127e-05]
 [9.9987519e-01]
 [9.9992335e-01


Hypothesis:
[[8.8291723e-05]
 [9.9988544e-01]
 [9.9992955e-01]
 [8.8377135e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.8247361e-05]
 [9.9988544e-01]
 [9.9992967e-01]
 [8.8332730e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.8203196e-05]
 [9.9988556e-01]
 [9.9992967e-01]
 [8.8288354e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.8158711e-05]
 [9.9988556e-01]
 [9.9992967e-01]
 [8.8243993e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.8114495e-05]
 [9.9988568e-01]
 [9.9992979e-01]
 [8.8199748e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.807007e-05]
 [9.998857e-01]
 [9.999298e-01]
 [8.815543e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.8025816e-05]
 [9.9988580e-01]
 [9.9992979e-01]
 [8.8111141e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.7981585e-05]
 [9.9988580e-01]
 [9.9992990e-01]
 [


Hypothesis:
[[8.1352984e-05]
 [9.9989438e-01]
 [9.9993515e-01]
 [8.1431994e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1312188e-05]
 [9.9989450e-01]
 [9.9993515e-01]
 [8.1391467e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1271413e-05]
 [9.9989450e-01]
 [9.9993515e-01]
 [8.1350503e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1230661e-05]
 [9.9989462e-01]
 [9.9993527e-01]
 [8.1309707e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1189923e-05]
 [9.9989462e-01]
 [9.9993527e-01]
 [8.1268932e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1149366e-05]
 [9.9989462e-01]
 [9.9993527e-01]
 [8.1228332e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1108665e-05]
 [9.9989474e-01]
 [9.9993539e-01]
 [8.1187594e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.1068152e-05]
 [9.9989474e-01]
 [9.9993539e-01


Hypothesis:
[[7.5955373e-05]
 [9.9990141e-01]
 [9.9993944e-01]
 [7.6028999e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5917211e-05]
 [9.9990141e-01]
 [9.9993944e-01]
 [7.5990800e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5879216e-05]
 [9.9990153e-01]
 [9.9993956e-01]
 [7.5952907e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5841235e-05]
 [9.9990153e-01]
 [9.9993956e-01]
 [7.5914897e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5803131e-05]
 [9.9990165e-01]
 [9.9993956e-01]
 [7.5876895e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5765194e-05]
 [9.9990165e-01]
 [9.9993956e-01]
 [7.5838776e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5727126e-05]
 [9.9990165e-01]
 [9.9993968e-01]
 [7.5800817e-05]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.5689364e-05]
 [9.9990177e-01]
 [9.9993968e-01

# Execute tensorboard

### 1. 터미널로 실행시 명령어

In [7]:
# tensorboard --logdir=./logs/xor_logs

### 2. jupyer notebook에서 명령어 바로 실행시키기
> **이렇게 실행시 주피터 노트북 다른 것 실행은 불가해짐 (계속 tensorboard만 실행)<br>
[Reference] <br> https://github.com/dokylee54/python-utils/blob/master/cmd-auto-execute/cmd_auto.py

In [11]:
import subprocess
import os

def cmd_auto_execute(bashcmd):

    """ 
    # arguments
    execute shell internal -> shell=True 
    change directory -> cwd="/path"
    # execute cmd with Popen
    process = subprocess.Popen(bashcmd.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    output = output.decode("utf-8") # binary format -> utf-8 decoding
    # Error handling
    if(error):
        print("ERROR: " + error)
        return
    """
    
    # execute cmd with subprocess.run()
    try:
        subprocess.run(" ".join(bashcmd.split()), stderr=subprocess.PIPE, shell=True, cwd="/Users/dokylee/Desktop/EWHA_NLP/modu-deep-lab")
    except output.stderr as e:
        print('Error: ' + e.decode("utf-8"))
    
    ## Print output
    print(output)

In [12]:
bashcmd = "tensorboard --logdir=./logs"
cmd_auto_execute(bashcmd)

NameError: name 'output' is not defined