# Tensorboard (Neural Net for XOR)

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

In [3]:
X = tf.placeholder(tf.float32, [None, 2], name="x")
Y = tf.placeholder(tf.float32, [None, 1], name="y")

with tf.name_scope("Layer1"):
    W1 = tf.Variable(tf.random_normal([2, 2]), name='weight_1')
    b1 = tf.Variable(tf.random_normal([2]), name='bias_1')
    
    layer1 = tf.sigmoid(tf.matmul(X, W1) + b1)
    
    tf.summary.histogram("W1", W1)
    tf.summary.histogram("b1", b1)
    tf.summary.histogram("Layer1", layer1)
    
with tf.name_scope("Layer2"):
    W2 = tf.Variable(tf.random_normal([2, 1]), name="weight_2")
    b2 = tf.Variable(tf.random_normal([1]), name="bias_2")
    
    hypothesis = tf.sigmoid(tf.matmul(layer1, W2) + b2)

    tf.summary.histogram("W2", W2)
    tf.summary.histogram("b2", b2)
    tf.summary.histogram("Hypothesis", hypothesis)
    
with tf.name_scope("Cost"):
    cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
    tf.summary.scalar("Cost", cost)
    
with tf.name_scope("Train"):
    train = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)
    
    
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

tf.summary.scalar("accuracy", accuracy)

with tf.Session() as sess:
    # tensorboard --logdir=./logs/xor_logs
    merged_summary = tf.summary.merge_all()
    
    writer = tf.summary.FileWriter("./logs/xor_logs_r0_01")
    writer.add_graph(sess.graph)
    
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        _, summary, cost_val = sess.run([train, merged_summary, cost], feed_dict={X: x_data, Y: y_data})
        
        writer.add_summary(summary, global_step=step)
        
        if step % 100 == 0:
            print(step, cost_val)
            
        h, p, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
        
        print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")

0 1.5390971

Hypothesis:
[[0.9365829 ]
 [0.9550955 ]
 [0.95168495]
 [0.96139765]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.93516713]
 [0.95384926]
 [0.9503406 ]
 [0.96027046]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.9337286]
 [0.9525753]
 [0.9489673]
 [0.9591157]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.93226707]
 [0.9512738 ]
 [0.9475651 ]
 [0.957933  ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.930783  ]
 [0.94994456]
 [0.94613385]
 [0.95672226]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.9292762 ]
 [0.9485873 ]
 [0.9446735 ]
 [0.95548314]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.92774695]
 [0.94720197]
 [0.9431839 ]
 [0.9542153 ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.9261951 ]
 [0.9457882 ]
 [0.9416649 ]
 [0.95291835]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0


Hypothesis:
[[0.5448436 ]
 [0.5281117 ]
 [0.5230229 ]
 [0.51262605]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.5439818 ]
 [0.52748746]
 [0.5224613 ]
 [0.51211244]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.54313815]
 [0.52688193]
 [0.5219192 ]
 [0.5116208 ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.54231226]
 [0.5262943 ]
 [0.52139616]
 [0.5111507 ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.54150367]
 [0.5257242 ]
 [0.52089167]
 [0.5107015 ]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.540712 ]
 [0.5251709]
 [0.5204051]
 [0.5102726]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.5399368 ]
 [0.524634  ]
 [0.5199361 ]
 [0.50986344]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.5391776 ]
 [0.5241128 ]
 [0.51948404]
 [0.50947344]] 
Predicted:
[[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
0.5

Hypothesis:
[[0.5384342 ]
 


Hypothesis:
[[0.4925564 ]
 [0.46101922]
 [0.56985164]
 [0.48832393]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49222335]
 [0.46044198]
 [0.5709697 ]
 [0.48792416]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49188253]
 [0.45986283]
 [0.57208407]
 [0.4875147 ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.4915339 ]
 [0.45928213]
 [0.5731942 ]
 [0.48709568]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49117738]
 [0.45869988]
 [0.5742996 ]
 [0.48666707]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49081308]
 [0.4581161 ]
 [0.57539946]
 [0.4862289 ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49044096]
 [0.45753112]
 [0.57649344]
 [0.48578116]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.49006104]
 [0.45694473]
 [0.57758087]
 [0.485324  ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0


Hypothesis:
[[0.41327238]
 [0.41788894]
 [0.6864338 ]
 [0.4075572 ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.4129353 ]
 [0.41810992]
 [0.686867  ]
 [0.40726966]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41259843]
 [0.4183358 ]
 [0.6872981 ]
 [0.40698132]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41226175]
 [0.41856667]
 [0.68772686]
 [0.40669203]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41192514]
 [0.41880253]
 [0.6881534 ]
 [0.40640172]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41158873]
 [0.41904333]
 [0.68857753]
 [0.40611035]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41125232]
 [0.41928905]
 [0.6889995 ]
 [0.4058178 ]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0.41091597]
 [0.4195398 ]
 [0.6894191 ]
 [0.40552402]] 
Predicted:
[[0.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.75

Hypothesis:
[[0


Hypothesis:
[[0.35546932]
 [0.510994  ]
 [0.7329558 ]
 [0.33160105]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35491395]
 [0.5121292 ]
 [0.7332472 ]
 [0.3308438 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35435483]
 [0.51326984]
 [0.733539  ]
 [0.33008507]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35379207]
 [0.51441574]
 [0.7338309 ]
 [0.32932487]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35322544]
 [0.5155669 ]
 [0.7341231 ]
 [0.32856312]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35265505]
 [0.51672316]
 [0.7344155 ]
 [0.32780004]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35208094]
 [0.5178844 ]
 [0.734708  ]
 [0.32703555]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.35150295]
 [0.51905066]
 [0.7350008 ]
 [0.32626975]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.3509213


Hypothesis:
[[0.23396076]
 [0.7136664 ]
 [0.7837866 ]
 [0.20779486]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.23328678]
 [0.714645  ]
 [0.7840825 ]
 [0.20720357]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.23261487]
 [0.71562004]
 [0.784378  ]
 [0.20661433]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.23194502]
 [0.71659094]
 [0.78467345]
 [0.2060272 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.2312772]
 [0.7175579]
 [0.7849686]
 [0.2054421]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.23061141]
 [0.7185212 ]
 [0.7852638 ]
 [0.2048591 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.22994775]
 [0.71948045]
 [0.7855587 ]
 [0.20427817]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.2292862 ]
 [0.7204358 ]
 [0.78585356]
 [0.2036993 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.22862677]
 


Hypothesis:
[[0.13945724]
 [0.8428712 ]
 [0.83668524]
 [0.12582889]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13912973]
 [0.8432913 ]
 [0.8369255 ]
 [0.12554356]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13880341]
 [0.8437096 ]
 [0.83716536]
 [0.12525916]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13847826]
 [0.8441263 ]
 [0.8374047 ]
 [0.12497587]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13815436]
 [0.8445412 ]
 [0.83764386]
 [0.12469358]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13783157]
 [0.84495443]
 [0.83788264]
 [0.12441225]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13751002]
 [0.845366  ]
 [0.83812106]
 [0.12413196]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.13718958]
 [0.8457758 ]
 [0.83835906]
 [0.12385257]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.1368703


Hypothesis:
[[0.09314936]
 [0.9000825 ]
 [0.87655795]
 [0.08511999]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09297592]
 [0.90028787]
 [0.8767323 ]
 [0.08496595]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09280299]
 [0.9004926 ]
 [0.8769063 ]
 [0.08481234]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09263057]
 [0.9006965 ]
 [0.8770799 ]
 [0.08465918]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09245867]
 [0.9008998 ]
 [0.87725335]
 [0.08450644]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09228729]
 [0.9011025 ]
 [0.8774264 ]
 [0.08435415]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09211635]
 [0.9013044 ]
 [0.8775992 ]
 [0.08420231]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.09194595]
 [0.9015057 ]
 [0.8777716 ]
 [0.08405089]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0917761

1.0

Hypothesis:
[[0.06862235]
 [0.9283783 ]
 [0.90331054]
 [0.06320149]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06851482]
 [0.92849904]
 [0.90343744]
 [0.06310478]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06840751]
 [0.9286194 ]
 [0.9035641 ]
 [0.06300823]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06830051]
 [0.92873955]
 [0.90369046]
 [0.06291199]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06819368]
 [0.9288593 ]
 [0.90381676]
 [0.06281591]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06808718]
 [0.9289787 ]
 [0.9039427 ]
 [0.06272008]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06798091]
 [0.92909783]
 [0.9040685 ]
 [0.06262447]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.06787489]
 [0.9292166 ]
 [0.90419406]
 [0.0625291 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.067


Hypothesis:
[[0.05204342]
 [0.946633  ]
 [0.9238737 ]
 [0.04822076]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05197301]
 [0.9467089 ]
 [0.9239653 ]
 [0.04815679]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05190277]
 [0.9467849 ]
 [0.9240568 ]
 [0.04809297]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05183261]
 [0.94686055]
 [0.92414814]
 [0.04802929]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05176262]
 [0.946936  ]
 [0.92423934]
 [0.04796575]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05169277]
 [0.9470114 ]
 [0.9243304 ]
 [0.04790235]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05162306]
 [0.9470866 ]
 [0.92442125]
 [0.04783904]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.05155346]
 [0.9471616 ]
 [0.9245119 ]
 [0.04777583]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0514840


Hypothesis:
[[0.04095531]
 [0.9584492 ]
 [0.9387389 ]
 [0.0381192 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04090611]
 [0.958501  ]
 [0.93880683]
 [0.03807424]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04085703]
 [0.9585526 ]
 [0.9388746 ]
 [0.03802933]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04080799]
 [0.95860416]
 [0.9389422 ]
 [0.03798454]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04075908]
 [0.95865566]
 [0.9390098 ]
 [0.03793978]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04071023]
 [0.9587069 ]
 [0.93907726]
 [0.03789514]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0406615 ]
 [0.95875823]
 [0.93914455]
 [0.03785058]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.04061284]
 [0.9588094 ]
 [0.93921185]
 [0.03780607]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0405642


Hypothesis:
[[0.03311293]
 [0.9666272 ]
 [0.9497641 ]
 [0.03093075]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03307693]
 [0.9666645 ]
 [0.9498157 ]
 [0.03089765]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03304099]
 [0.96670157]
 [0.94986725]
 [0.0308646 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03300506]
 [0.9667387 ]
 [0.9499185 ]
 [0.0308316 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03296922]
 [0.9667758 ]
 [0.94996995]
 [0.03079861]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03293344]
 [0.9668128 ]
 [0.95002115]
 [0.03076573]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03289769]
 [0.9668496 ]
 [0.95007235]
 [0.03073288]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.03286201]
 [0.9668865 ]
 [0.9501235 ]
 [0.03070008]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0328264


Hypothesis:
[[0.02705949]
 [0.97284657]
 [0.95854384]
 [0.02535463]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02703256]
 [0.9728741 ]
 [0.9585835 ]
 [0.02532976]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02700566]
 [0.9729015 ]
 [0.9586229 ]
 [0.02530492]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02697878]
 [0.97292906]
 [0.95866245]
 [0.02528009]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02695195]
 [0.97295636]
 [0.9587018 ]
 [0.02525533]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02692516]
 [0.9729838 ]
 [0.95874125]
 [0.02523058]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02689841]
 [0.9730111 ]
 [0.95878047]
 [0.02520588]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02687168]
 [0.9730383 ]
 [0.9588198 ]
 [0.02518121]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0268449


Hypothesis:
[[0.02242504]
 [0.97755903]
 [0.9654115 ]
 [0.02106784]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02240435]
 [0.97758   ]
 [0.96544236]
 [0.02104867]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0223837 ]
 [0.97760093]
 [0.96547335]
 [0.0210295 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02236307]
 [0.9776218 ]
 [0.96550417]
 [0.02101039]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02234245]
 [0.97764266]
 [0.9655349 ]
 [0.0209913 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02232187]
 [0.9776635 ]
 [0.96556574]
 [0.02097221]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02230133]
 [0.9776844 ]
 [0.9655965 ]
 [0.02095316]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.02228078]
 [0.97770506]
 [0.9656272 ]
 [0.02093414]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0222602


Hypothesis:
[[0.01884264]
 [0.9811761 ]
 [0.97079957]
 [0.01774252]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01882636]
 [0.98119235]
 [0.9708241 ]
 [0.01772739]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01881011]
 [0.9812088 ]
 [0.97084874]
 [0.01771229]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01879387]
 [0.9812252 ]
 [0.97087336]
 [0.01769721]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01877768]
 [0.98124146]
 [0.97089785]
 [0.01768213]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01876149]
 [0.9812578 ]
 [0.97092235]
 [0.01766707]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01874531]
 [0.98127407]
 [0.97094685]
 [0.01765204]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01872914]
 [0.9812903 ]
 [0.97097135]
 [0.01763701]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.018713 


Hypothesis:
[[0.01606413]
 [0.98396814]
 [0.9750224 ]
 [0.01515575]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01605102]
 [0.9839813 ]
 [0.97504246]
 [0.01514352]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01603793]
 [0.98399436]
 [0.9750624 ]
 [0.01513131]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01602484]
 [0.98400754]
 [0.97508234]
 [0.0151191 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01601177]
 [0.9840206 ]
 [0.9751023 ]
 [0.0151069 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0159987 ]
 [0.9840337 ]
 [0.9751222 ]
 [0.01509474]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01598566]
 [0.98404676]
 [0.9751422 ]
 [0.01508257]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01597264]
 [0.98405993]
 [0.975162  ]
 [0.01507043]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0159596


Hypothesis:
[[0.01371246]
 [0.98632324]
 [0.97862375]
 [0.01296057]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01370183]
 [0.9863339 ]
 [0.9786401 ]
 [0.01295063]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01369122]
 [0.9863446 ]
 [0.9786564 ]
 [0.01294072]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01368061]
 [0.9863551 ]
 [0.9786726 ]
 [0.01293082]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01367002]
 [0.9863658 ]
 [0.9786889 ]
 [0.0129209 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01365944]
 [0.98637635]
 [0.9787052 ]
 [0.01291101]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01364887]
 [0.9863869 ]
 [0.97872144]
 [0.01290112]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01363831]
 [0.98639745]
 [0.9787377 ]
 [0.01289125]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0136277


Hypothesis:
[[0.01178508]
 [0.9882492 ]
 [0.9815926 ]
 [0.01115715]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01177635]
 [0.9882578 ]
 [0.98160607]
 [0.01114897]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01176762]
 [0.9882665 ]
 [0.9816195 ]
 [0.01114082]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01175893]
 [0.9882753 ]
 [0.98163295]
 [0.01113266]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01175022]
 [0.9882839 ]
 [0.98164636]
 [0.01112449]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01174153]
 [0.98829263]
 [0.9816598 ]
 [0.01111638]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01173286]
 [0.9883012 ]
 [0.98167324]
 [0.01110824]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01172418]
 [0.98830986]
 [0.9816866 ]
 [0.01110011]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0117155


Hypothesis:
[[0.01025208]
 [0.9897786 ]
 [0.98396415]
 [0.00971972]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01024479]
 [0.9897858 ]
 [0.9839754 ]
 [0.00971289]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0102375 ]
 [0.98979306]
 [0.98398674]
 [0.00970604]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01023022]
 [0.9898003 ]
 [0.98399806]
 [0.00969922]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01022295]
 [0.98980767]
 [0.98400927]
 [0.00969238]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01021568]
 [0.9898149 ]
 [0.9840206 ]
 [0.00968556]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01020842]
 [0.98982215]
 [0.98403186]
 [0.00967874]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.01020116]
 [0.98982924]
 [0.98404306]
 [0.00967193]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0101939


Hypothesis:
[[0.00903823]
 [0.99098843]
 [0.98584795]
 [0.00857947]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00903201]
 [0.99099463]
 [0.9858576 ]
 [0.00857363]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0090258 ]
 [0.99100083]
 [0.9858673 ]
 [0.00856778]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00901957]
 [0.99100703]
 [0.9858769 ]
 [0.00856193]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00901336]
 [0.9910132 ]
 [0.9858866 ]
 [0.0085561 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00900716]
 [0.9910194 ]
 [0.98589617]
 [0.00855027]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00900097]
 [0.9910255 ]
 [0.98590577]
 [0.00854445]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00899477]
 [0.99103177]
 [0.9859154 ]
 [0.00853862]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0089885


Hypothesis:
[[0.00798835]
 [0.99203426]
 [0.9874812 ]
 [0.00759166]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00798302]
 [0.99203956]
 [0.9874894 ]
 [0.00758663]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00797768]
 [0.9920448 ]
 [0.9874978 ]
 [0.00758161]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00797236]
 [0.99205023]
 [0.98750603]
 [0.00757659]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00796702]
 [0.9920555 ]
 [0.9875143 ]
 [0.00757158]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0079617 ]
 [0.9920608 ]
 [0.98752266]
 [0.00756657]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00795639]
 [0.9920661 ]
 [0.9875309 ]
 [0.00756157]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
3700 0.009022891

Hypothesis:
[[0.00795108]
 [0.99207133]
 [0.9875392 ]
 [0.00755656]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypoth


Hypothesis:
[[0.0070482 ]
 [0.9929704 ]
 [0.9889466 ]
 [0.00670572]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00704362]
 [0.992975  ]
 [0.9889537 ]
 [0.00670141]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00703905]
 [0.99297947]
 [0.9889608 ]
 [0.00669709]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00703448]
 [0.99298406]
 [0.98896796]
 [0.00669278]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00702991]
 [0.99298865]
 [0.98897505]
 [0.00668847]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00702534]
 [0.9929932 ]
 [0.98898226]
 [0.00668417]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00702078]
 [0.99299765]
 [0.9889893 ]
 [0.00667986]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00701623]
 [0.99300224]
 [0.9889964 ]
 [0.00667556]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0070116


Hypothesis:
[[0.00621165]
 [0.99380326]
 [0.9902526 ]
 [0.00591624]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00620772]
 [0.99380714]
 [0.9902588 ]
 [0.00591253]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00620379]
 [0.9938111 ]
 [0.990265  ]
 [0.00590882]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00619987]
 [0.99381495]
 [0.9902711 ]
 [0.00590512]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00619595]
 [0.9938188 ]
 [0.9902772 ]
 [0.00590141]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00619203]
 [0.9938228 ]
 [0.99028337]
 [0.00589771]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00618811]
 [0.9938267 ]
 [0.99028945]
 [0.00589401]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0061842 ]
 [0.9938306 ]
 [0.9902955 ]
 [0.00589032]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0061802


Hypothesis:
[[0.00550839]
 [0.9945034 ]
 [0.9913521 ]
 [0.00525164]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00550499]
 [0.9945068 ]
 [0.99135745]
 [0.00524842]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00550159]
 [0.99451005]
 [0.99136275]
 [0.0052452 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00549819]
 [0.9945135 ]
 [0.9913681 ]
 [0.00524198]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00549479]
 [0.9945169 ]
 [0.99137336]
 [0.00523876]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00549139]
 [0.99452037]
 [0.99137866]
 [0.00523555]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00548799]
 [0.99452364]
 [0.991384  ]
 [0.00523233]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0054846 ]
 [0.99452704]
 [0.99138933]
 [0.00522914]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0054812


Hypothesis:
[[0.00491527]
 [0.99509394]
 [0.99228036]
 [0.0046904 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0049123 ]
 [0.99509686]
 [0.992285  ]
 [0.00468759]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00490932]
 [0.99509984]
 [0.9922896 ]
 [0.00468477]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00490635]
 [0.99510276]
 [0.9922943 ]
 [0.00468194]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00490337]
 [0.99510574]
 [0.992299  ]
 [0.00467913]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0049004 ]
 [0.99510866]
 [0.9923036 ]
 [0.00467632]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00489742]
 [0.99511164]
 [0.99230826]
 [0.00467351]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00489446]
 [0.99511456]
 [0.99231297]
 [0.0046707 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0048915


Hypothesis:
[[0.00439547]
 [0.9956115 ]
 [0.99309456]
 [0.00419798]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00439285]
 [0.99561405]
 [0.9930987 ]
 [0.00419549]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00439023]
 [0.9956167 ]
 [0.9931028 ]
 [0.00419302]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00438762]
 [0.99561924]
 [0.9931068 ]
 [0.00419054]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00438502]
 [0.99562186]
 [0.9931109 ]
 [0.00418806]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0043824]
 [0.9956245]
 [0.993115 ]
 [0.0041856]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00437981]
 [0.99562705]
 [0.9931191 ]
 [0.00418312]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00437719]
 [0.99562967]
 [0.99312323]
 [0.00418065]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00437459]
 


Hypothesis:
[[0.00393817]
 [0.996067  ]
 [0.9938113 ]
 [0.00376429]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00393587]
 [0.9960692 ]
 [0.99381495]
 [0.00376209]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00393356]
 [0.99607146]
 [0.9938186 ]
 [0.0037599 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00393125]
 [0.99607384]
 [0.9938221 ]
 [0.00375771]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00392895]
 [0.99607605]
 [0.9938258 ]
 [0.00375553]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00392665]
 [0.99607843]
 [0.9938294 ]
 [0.00375334]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00392435]
 [0.9960807 ]
 [0.99383295]
 [0.00375117]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00392205]
 [0.9960829 ]
 [0.9938366 ]
 [0.00374899]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0039197


Hypothesis:
[[0.00352836]
 [0.99647516]
 [0.9944541 ]
 [0.00337522]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00352632]
 [0.9964772 ]
 [0.99445724]
 [0.00337328]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00352429]
 [0.9964792 ]
 [0.99446046]
 [0.00337135]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00352225]
 [0.9964812 ]
 [0.9944636 ]
 [0.00336942]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00352022]
 [0.9964832 ]
 [0.99446684]
 [0.00336748]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00351819]
 [0.99648523]
 [0.99447   ]
 [0.00336556]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00351617]
 [0.9964874 ]
 [0.99447316]
 [0.00336363]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00351414]
 [0.99648935]
 [0.9944764 ]
 [0.00336171]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0035121


Hypothesis:
[[0.00314999]
 [0.9968522 ]
 [0.9950478 ]
 [0.00301563]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0031482 ]
 [0.996854  ]
 [0.9950506 ]
 [0.00301394]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314641]
 [0.99685574]
 [0.99505347]
 [0.00301223]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314462]
 [0.9968575 ]
 [0.99505615]
 [0.00301053]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314284]
 [0.9968593 ]
 [0.995059  ]
 [0.00300883]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00314105]
 [0.9968611 ]
 [0.9950618 ]
 [0.00300714]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00313926]
 [0.9968629 ]
 [0.9950647 ]
 [0.00300544]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00313748]
 [0.9968646 ]
 [0.99506736]
 [0.00300373]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0031356


Hypothesis:
[[0.00282761]
 [0.99717355]
 [0.9955539 ]
 [0.00270896]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00282603]
 [0.9971751 ]
 [0.9955564 ]
 [0.00270745]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00282444]
 [0.99717665]
 [0.99555886]
 [0.00270594]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00282285]
 [0.9971783 ]
 [0.99556136]
 [0.00270443]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00282126]
 [0.99717987]
 [0.99556386]
 [0.00270292]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00281968]
 [0.9971814 ]
 [0.9955663 ]
 [0.00270141]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0028181 ]
 [0.9971831 ]
 [0.9955688 ]
 [0.00269991]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00281652]
 [0.9971846 ]
 [0.9955713 ]
 [0.00269841]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0028149


Hypothesis:
[[0.0025316 ]
 [0.9974687 ]
 [0.9960187 ]
 [0.00242711]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0025302 ]
 [0.99747   ]
 [0.996021  ]
 [0.00242577]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0025288 ]
 [0.99747145]
 [0.9960232 ]
 [0.00242443]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00252739]
 [0.9974728 ]
 [0.9960253 ]
 [0.00242309]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00252599]
 [0.99747425]
 [0.9960276 ]
 [0.00242176]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00252459]
 [0.9974757 ]
 [0.99602985]
 [0.00242043]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00252318]
 [0.997477  ]
 [0.99603194]
 [0.00241909]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00252179]
 [0.9974784 ]
 [0.9960342 ]
 [0.00241776]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0025203


Hypothesis:
[[0.00233137]
 [0.9976683 ]
 [0.99633324]
 [0.0022363 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00233008]
 [0.99766964]
 [0.99633527]
 [0.00223508]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0023288 ]
 [0.99767095]
 [0.9963373 ]
 [0.00223385]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00232752]
 [0.99767214]
 [0.9963393 ]
 [0.00223263]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00232624]
 [0.99767345]
 [0.9963413 ]
 [0.00223141]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00232496]
 [0.99767476]
 [0.9963433 ]
 [0.00223019]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00232368]
 [0.9976761 ]
 [0.99634534]
 [0.00222897]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0023224 ]
 [0.99767727]
 [0.99634737]
 [0.00222775]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0023211


Hypothesis:
[[0.00212731]
 [0.9978719 ]
 [0.9966539 ]
 [0.00204172]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212615]
 [0.99787307]
 [0.9966557 ]
 [0.00204061]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212499]
 [0.99787426]
 [0.9966576 ]
 [0.0020395 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212383]
 [0.99787545]
 [0.9966594 ]
 [0.00203839]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212267]
 [0.9978765 ]
 [0.9966613 ]
 [0.00203729]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212151]
 [0.9978777 ]
 [0.99666303]
 [0.00203618]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00212035]
 [0.9978789 ]
 [0.9966648 ]
 [0.00203508]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00211919]
 [0.9978801 ]
 [0.9966667 ]
 [0.00203397]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0021180


Hypothesis:
[[0.0019289 ]
 [0.99806994]
 [0.9969658 ]
 [0.00185237]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192785]
 [0.998071  ]
 [0.9969675 ]
 [0.00185136]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192681]
 [0.9980719 ]
 [0.99696904]
 [0.00185037]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192576]
 [0.998073  ]
 [0.99697065]
 [0.00184937]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192472]
 [0.99807405]
 [0.9969723 ]
 [0.00184838]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192368]
 [0.9980751 ]
 [0.996974  ]
 [0.00184738]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192263]
 [0.9980762 ]
 [0.99697566]
 [0.00184639]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00192159]
 [0.99807715]
 [0.9969773 ]
 [0.0018454 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0019205


Hypothesis:
[[0.00174187]
 [0.9982566 ]
 [0.99725974]
 [0.00167375]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00174093]
 [0.9982576 ]
 [0.9972613 ]
 [0.00167286]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00174   ]
 [0.9982584 ]
 [0.9972627 ]
 [0.00167197]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00173906]
 [0.99825937]
 [0.99726415]
 [0.00167107]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00173813]
 [0.9982603 ]
 [0.9972657 ]
 [0.00167018]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0017372 ]
 [0.9982613 ]
 [0.9972671 ]
 [0.00166929]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00173626]
 [0.9982622 ]
 [0.99726856]
 [0.0016684 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00173533]
 [0.9982632 ]
 [0.99727005]
 [0.00166751]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0017344


Hypothesis:
[[0.00158515]
 [0.9984131 ]
 [0.9975062 ]
 [0.00152397]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0015843 ]
 [0.9984139 ]
 [0.99750745]
 [0.00152316]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00158346]
 [0.99841475]
 [0.99750876]
 [0.00152235]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00158261]
 [0.9984156 ]
 [0.9975102 ]
 [0.00152155]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00158177]
 [0.9984164 ]
 [0.9975115 ]
 [0.00152074]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00158093]
 [0.99841726]
 [0.9975128 ]
 [0.00151994]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00158008]
 [0.9984181 ]
 [0.9975141 ]
 [0.00151913]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00157924]
 [0.9984189 ]
 [0.99751544]
 [0.00151832]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0015784


Hypothesis:
[[0.00142589]
 [0.9985721 ]
 [0.99775666]
 [0.00137166]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142513]
 [0.99857295]
 [0.99775785]
 [0.00137093]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142438]
 [0.99857366]
 [0.997759  ]
 [0.00137021]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142362]
 [0.9985744 ]
 [0.9977602 ]
 [0.00136949]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142287]
 [0.9985752 ]
 [0.99776137]
 [0.00136877]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142211]
 [0.9985759 ]
 [0.99776256]
 [0.00136804]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142136]
 [0.99857664]
 [0.99776375]
 [0.00136732]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00142061]
 [0.9985775 ]
 [0.99776495]
 [0.0013666 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0014198


Hypothesis:
[[0.00128284]
 [0.99871504]
 [0.99798155]
 [0.00123474]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00128216]
 [0.99871576]
 [0.9979826 ]
 [0.0012341 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00128149]
 [0.9987165 ]
 [0.9979837 ]
 [0.00123345]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00128081]
 [0.99871707]
 [0.99798477]
 [0.0012328 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00128014]
 [0.9987178 ]
 [0.99798584]
 [0.00123216]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00127946]
 [0.9987185 ]
 [0.9979869 ]
 [0.00123151]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00127879]
 [0.9987191 ]
 [0.997988  ]
 [0.00123087]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00127812]
 [0.9987198 ]
 [0.99798906]
 [0.00123022]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0012774


Hypothesis:
[[0.00115547]
 [0.9988424 ]
 [0.99818194]
 [0.00111275]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115486]
 [0.99884295]
 [0.99818283]
 [0.00111217]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115426]
 [0.99884355]
 [0.9981838 ]
 [0.00111159]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115365]
 [0.99884415]
 [0.99818474]
 [0.00111101]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115305]
 [0.99884474]
 [0.9981857 ]
 [0.00111043]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115244]
 [0.99884534]
 [0.99818665]
 [0.00110986]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115184]
 [0.99884593]
 [0.9981876 ]
 [0.00110928]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00115124]
 [0.99884653]
 [0.99818856]
 [0.0011087 ]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0011506


Hypothesis:
[[0.00104677]
 [0.99895096]
 [0.998353  ]
 [0.00100858]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104622]
 [0.99895155]
 [0.99835384]
 [0.00100805]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104568]
 [0.99895203]
 [0.9983546 ]
 [0.00100753]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104513]
 [0.9989526 ]
 [0.99835545]
 [0.00100701]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104459]
 [0.9989532 ]
 [0.9983563 ]
 [0.00100649]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104404]
 [0.9989537 ]
 [0.99835724]
 [0.00100597]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0010435 ]
 [0.9989543 ]
 [0.9983581 ]
 [0.00100544]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.00104296]
 [0.9989548 ]
 [0.9983589 ]
 [0.00100492]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[0.0010424


Hypothesis:
[[9.4724895e-04]
 [9.9905056e-01]
 [9.9850947e-01]
 [9.1314176e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4675587e-04]
 [9.9905103e-01]
 [9.9851030e-01]
 [9.1266807e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.462631e-04]
 [9.990515e-01]
 [9.985110e-01]
 [9.121964e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4577309e-04]
 [9.9905199e-01]
 [9.9851185e-01]
 [9.1172598e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4528351e-04]
 [9.9905246e-01]
 [9.9851257e-01]
 [9.1125479e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4479055e-04]
 [9.9905294e-01]
 [9.9851340e-01]
 [9.1078295e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4430055e-04]
 [9.9905342e-01]
 [9.9851412e-01]
 [9.1031409e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[9.4381347e-04]
 [9.9905401e-01]
 [9.9851495e-01]
 [


Hypothesis:
[[8.5667492e-04]
 [9.9914110e-01]
 [9.9865204e-01]
 [8.2622614e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5623219e-04]
 [9.9914157e-01]
 [9.9865270e-01]
 [8.2580146e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5578969e-04]
 [9.9914205e-01]
 [9.9865341e-01]
 [8.2537788e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5534831e-04]
 [9.9914241e-01]
 [9.9865401e-01]
 [8.2495436e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.549063e-04]
 [9.991429e-01]
 [9.986547e-01]
 [8.245297e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5446442e-04]
 [9.9914336e-01]
 [9.9865544e-01]
 [8.2410593e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5402449e-04]
 [9.9914372e-01]
 [9.9865615e-01]
 [8.2368316e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[8.5358229e-04]
 [9.9914420e-01]
 [9.9865687e-01]
 [


Hypothesis:
[[7.7946973e-04]
 [9.9921834e-01]
 [9.9877352e-01]
 [7.5210113e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.790691e-04]
 [9.992188e-01]
 [9.987741e-01]
 [7.517145e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.7866792e-04]
 [9.9921918e-01]
 [9.9877471e-01]
 [7.5132964e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.7826547e-04]
 [9.9921954e-01]
 [9.9877542e-01]
 [7.5094489e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.778647e-04]
 [9.992200e-01]
 [9.987760e-01]
 [7.505596e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.7746564e-04]
 [9.9922037e-01]
 [9.9877661e-01]
 [7.5017381e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.7706389e-04]
 [9.9922073e-01]
 [9.9877721e-01]
 [7.4978964e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.7666366e-04]
 [9.9922121e-01]
 [9.9877793e-01]
 [7.49


Hypothesis:
[[7.0762716e-04]
 [9.9929023e-01]
 [9.9888653e-01]
 [6.8308203e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0726138e-04]
 [9.9929059e-01]
 [9.9888712e-01]
 [6.8273285e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0689991e-04]
 [9.9929094e-01]
 [9.9888772e-01]
 [6.8238447e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0653652e-04]
 [9.9929130e-01]
 [9.9888831e-01]
 [6.8203575e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0617470e-04]
 [9.9929166e-01]
 [9.9888879e-01]
 [6.8168837e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0581172e-04]
 [9.9929202e-01]
 [9.9888939e-01]
 [6.8133924e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0545095e-04]
 [9.9929237e-01]
 [9.9888998e-01]
 [6.8099168e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[7.0508767e-04]
 [9.9929273e-01]
 [9.9889058e-01


Hypothesis:
[[6.419454e-04]
 [9.993560e-01]
 [9.989899e-01]
 [6.199494e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.4161752e-04]
 [9.9935633e-01]
 [9.9899036e-01]
 [6.1963400e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.4128864e-04]
 [9.9935669e-01]
 [9.9899095e-01]
 [6.1931816e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.4096117e-04]
 [9.9935704e-01]
 [9.9899143e-01]
 [6.1900303e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.4063375e-04]
 [9.9935728e-01]
 [9.9899191e-01]
 [6.1868748e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.4030540e-04]
 [9.9935764e-01]
 [9.9899250e-01]
 [6.1837264e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.3997717e-04]
 [9.9935800e-01]
 [9.9899298e-01]
 [6.1805861e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[6.3965027e-04]
 [9.9935836e-01]
 [9.9899346e-01]
 [


Hypothesis:
[[5.801495e-04]
 [9.994179e-01]
 [9.990871e-01]
 [5.605214e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0
8400 0.00065914245

Hypothesis:
[[5.7985511e-04]
 [9.9941826e-01]
 [9.9908757e-01]
 [5.6023587e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.7955756e-04]
 [9.9941850e-01]
 [9.9908805e-01]
 [5.5995001e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.7926186e-04]
 [9.9941885e-01]
 [9.9908853e-01]
 [5.5966532e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.789668e-04]
 [9.994191e-01]
 [9.990890e-01]
 [5.593808e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.7867140e-04]
 [9.9941945e-01]
 [9.9908948e-01]
 [5.5909646e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.7837501e-04]
 [9.9941969e-01]
 [9.9908996e-01]
 [5.5881217e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.7807990e-04]
 [9.9941993e-01]
 [9.


Hypothesis:
[[5.2606122e-04]
 [9.9947208e-01]
 [9.9917233e-01]
 [5.0847337e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2579405e-04]
 [9.9947232e-01]
 [9.9917263e-01]
 [5.0821609e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2552548e-04]
 [9.9947268e-01]
 [9.9917310e-01]
 [5.0795794e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2525755e-04]
 [9.9947292e-01]
 [9.9917346e-01]
 [5.0770090e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2499078e-04]
 [9.9947315e-01]
 [9.9917394e-01]
 [5.0744304e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.247226e-04]
 [9.994734e-01]
 [9.991743e-01]
 [5.071853e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2445661e-04]
 [9.9947375e-01]
 [9.9917477e-01]
 [5.0692866e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[5.2418973e-04]
 [9.9947399e-01]
 [9.9917525e-01]
 [


Hypothesis:
[[4.7736557e-04]
 [9.9952090e-01]
 [9.9924892e-01]
 [4.6159243e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.7712220e-04]
 [9.9952114e-01]
 [9.9924928e-01]
 [4.6135930e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.7687988e-04]
 [9.9952137e-01]
 [9.9924964e-01]
 [4.6112583e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.766390e-04]
 [9.995216e-01]
 [9.992500e-01]
 [4.608916e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.7639600e-04]
 [9.9952185e-01]
 [9.9925035e-01]
 [4.6065837e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.761531e-04]
 [9.995221e-01]
 [9.992508e-01]
 [4.604257e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.759117e-04]
 [9.995223e-01]
 [9.992512e-01]
 [4.601927e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.7567044e-04]
 [9.9952257e-01]
 [9.9925154e-01]
 [4.599589


Hypothesis:
[[4.3349218e-04]
 [9.9956483e-01]
 [9.9931800e-01]
 [4.1933396e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3327324e-04]
 [9.9956506e-01]
 [9.9931836e-01]
 [4.1912255e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3305234e-04]
 [9.9956530e-01]
 [9.9931872e-01]
 [4.1891047e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3283359e-04]
 [9.9956542e-01]
 [9.9931908e-01]
 [4.1869926e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3261252e-04]
 [9.9956566e-01]
 [9.9931931e-01]
 [4.1848738e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3239442e-04]
 [9.9956590e-01]
 [9.9931967e-01]
 [4.1827682e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3217477e-04]
 [9.9956614e-01]
 [9.9932003e-01]
 [4.1806474e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[4.3195646e-04]
 [9.9956638e-01]
 [9.9932039e-01


Hypothesis:
[[3.9412038e-04]
 [9.9960428e-01]
 [9.9937987e-01]
 [3.8139298e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9392168e-04]
 [9.9960452e-01]
 [9.9938023e-01]
 [3.8120142e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9372232e-04]
 [9.9960464e-01]
 [9.9938047e-01]
 [3.8100887e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9352343e-04]
 [9.9960488e-01]
 [9.9938083e-01]
 [3.8081640e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9332389e-04]
 [9.9960512e-01]
 [9.9938118e-01]
 [3.8062478e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9312488e-04]
 [9.9960524e-01]
 [9.9938142e-01]
 [3.8043287e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9292630e-04]
 [9.9960548e-01]
 [9.9938178e-01]
 [3.8024146e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.9272706e-04]
 [9.9960572e-01]
 [9.9938214e-01


Hypothesis:
[[3.5767065e-04]
 [9.9964082e-01]
 [9.9943727e-01]
 [3.4625095e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5748997e-04]
 [9.9964094e-01]
 [9.9943763e-01]
 [3.4607638e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5730872e-04]
 [9.9964118e-01]
 [9.9943787e-01]
 [3.4590258e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5712926e-04]
 [9.9964130e-01]
 [9.9943811e-01]
 [3.4572915e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5694853e-04]
 [9.9964154e-01]
 [9.9943846e-01]
 [3.4555548e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5676820e-04]
 [9.9964166e-01]
 [9.9943870e-01]
 [3.4538095e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5658901e-04]
 [9.9964190e-01]
 [9.9943894e-01]
 [3.4520746e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.5640856e-04]
 [9.9964213e-01]
 [9.9943930e-01


Hypothesis:
[[3.2382278e-04]
 [9.9967480e-01]
 [9.9949062e-01]
 [3.1360329e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2366041e-04]
 [9.9967492e-01]
 [9.9949086e-01]
 [3.1344549e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2349661e-04]
 [9.9967504e-01]
 [9.9949110e-01]
 [3.1328833e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2333352e-04]
 [9.9967527e-01]
 [9.9949133e-01]
 [3.1313067e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2317109e-04]
 [9.9967539e-01]
 [9.9949157e-01]
 [3.1297366e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2300755e-04]
 [9.9967563e-01]
 [9.9949181e-01]
 [3.1281618e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2284501e-04]
 [9.9967575e-01]
 [9.9949205e-01]
 [3.1265905e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[3.2268188e-04]
 [9.9967587e-01]
 [9.9949241e-01


Hypothesis:
[[2.9514055e-04]
 [9.9970347e-01]
 [9.9953568e-01]
 [2.8592517e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9499255e-04]
 [9.9970359e-01]
 [9.9953592e-01]
 [2.8578183e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9484410e-04]
 [9.9970371e-01]
 [9.9953616e-01]
 [2.8563855e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9469628e-04]
 [9.9970394e-01]
 [9.9953640e-01]
 [2.8549533e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9454741e-04]
 [9.9970406e-01]
 [9.9953663e-01]
 [2.8535168e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9439889e-04]
 [9.9970418e-01]
 [9.9953687e-01]
 [2.8520942e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9425102e-04]
 [9.9970430e-01]
 [9.9953711e-01]
 [2.8506614e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.9410294e-04]
 [9.9970454e-01]
 [9.9953735e-01


Hypothesis:
[[2.6917050e-04]
 [9.9972957e-01]
 [9.9957663e-01]
 [2.6085434e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6903607e-04]
 [9.9972969e-01]
 [9.9957675e-01]
 [2.6072306e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6890016e-04]
 [9.9972981e-01]
 [9.9957699e-01]
 [2.6059235e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6876482e-04]
 [9.9972993e-01]
 [9.9957722e-01]
 [2.6046220e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6862955e-04]
 [9.9973005e-01]
 [9.9957746e-01]
 [2.6033109e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6849436e-04]
 [9.9973017e-01]
 [9.9957770e-01]
 [2.6020058e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6836025e-04]
 [9.9973029e-01]
 [9.9957782e-01]
 [2.6007011e-04]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

Hypothesis:
[[2.6822419e-04]
 [9.9973053e-01]
 [9.9957806e-01

# Execute tensorboard

### 1. 터미널로 실행시 명령어

In [4]:
# tensorboard --logdir=./logs/xor_logs

### 2. jupyer notebook에서 명령어 바로 실행시키기
> **이렇게 실행시 주피터 노트북 다른 것 실행은 불가해짐 (계속 tensorboard만 실행)<br>
[Reference] <br> https://github.com/dokylee54/python-utils/blob/master/cmd-auto-execute/cmd_auto.py

In [5]:
import subprocess
import os

def cmd_auto_execute(bashcmd):

    """ 
    # arguments
    execute shell internal -> shell=True 
    change directory -> cwd="/path"
    # execute cmd with Popen
    process = subprocess.Popen(bashcmd.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    output = output.decode("utf-8") # binary format -> utf-8 decoding
    # Error handling
    if(error):
        print("ERROR: " + error)
        return
    """
    
    # execute cmd with subprocess.run()
    try:
        subprocess.run(" ".join(bashcmd.split()), stderr=subprocess.PIPE, shell=True, cwd="/Users/dokylee/Desktop/EWHA_NLP/modu-deep-lab")
    except output.stderr as e:
        print('Error: ' + e.decode("utf-8"))
    
    ## Print output
    print(output)

In [ ]:
bashcmd = "tensorboard --logdir=./logs"
cmd_auto_execute(bashcmd)